// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acs_event.proto

package net.zdsoft.officework.mqreceive;

import java.util.Map;

import com.alibaba.fastjson.JSONObject;
import com.google.protobuf.Descriptors.FieldDescriptor;

public final class AcsEvent {
	private AcsEvent() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface AccessEventLogOrBuilder extends
	// @@protoc_insertion_point(interface_extends:net.zdsoft.officework.mqreceive.AccessEventLog)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>optional int32 event_code = 1;</code>
		 *
		 * <pre>
		 * 事件码，门禁原始定义事件码
		 * </pre>
		 */
		boolean hasEventCode();

		/**
		 * <code>optional int32 event_code = 1;</code>
		 *
		 * <pre>
		 * 事件码，门禁原始定义事件码
		 * </pre>
		 */
		int getEventCode();

		/**
		 * <code>optional int32 device_id = 2;</code>
		 *
		 * <pre>
		 * 产生事件的设备Id，门禁刷卡事件就是读卡器Id
		 * </pre>
		 */
		boolean hasDeviceId();

		/**
		 * <code>optional int32 device_id = 2;</code>
		 *
		 * <pre>
		 * 产生事件的设备Id，门禁刷卡事件就是读卡器Id
		 * </pre>
		 */
		int getDeviceId();

		/**
		 * <code>optional int32 device_type = 3;</code>
		 *
		 * <pre>
		 * 产生事件的设备类型
		 * </pre>
		 */
		boolean hasDeviceType();

		/**
		 * <code>optional int32 device_type = 3;</code>
		 *
		 * <pre>
		 * 产生事件的设备类型
		 * </pre>
		 */
		int getDeviceType();

		/**
		 * <code>optional string device_name = 4;</code>
		 *
		 * <pre>
		 * 产生事件的设备名称
		 * </pre>
		 */
		boolean hasDeviceName();

		/**
		 * <code>optional string device_name = 4;</code>
		 *
		 * <pre>
		 * 产生事件的设备名称
		 * </pre>
		 */
		java.lang.String getDeviceName();

		/**
		 * <code>optional string device_name = 4;</code>
		 *
		 * <pre>
		 * 产生事件的设备名称
		 * </pre>
		 */
		com.google.protobuf.ByteString getDeviceNameBytes();

		/**
		 * <code>optional string event_card = 5;</code>
		 *
		 * <pre>
		 * 卡号
		 * </pre>
		 */
		boolean hasEventCard();

		/**
		 * <code>optional string event_card = 5;</code>
		 *
		 * <pre>
		 * 卡号
		 * </pre>
		 */
		java.lang.String getEventCard();

		/**
		 * <code>optional string event_card = 5;</code>
		 *
		 * <pre>
		 * 卡号
		 * </pre>
		 */
		com.google.protobuf.ByteString getEventCardBytes();

		/**
		 * <code>optional int32 person_id = 6;</code>
		 *
		 * <pre>
		 * 人员Id
		 * </pre>
		 */
		boolean hasPersonId();

		/**
		 * <code>optional int32 person_id = 6;</code>
		 *
		 * <pre>
		 * 人员Id
		 * </pre>
		 */
		int getPersonId();

		/**
		 * <code>optional string person_name = 7;</code>
		 *
		 * <pre>
		 * 人员名称
		 * </pre>
		 */
		boolean hasPersonName();

		/**
		 * <code>optional string person_name = 7;</code>
		 *
		 * <pre>
		 * 人员名称
		 * </pre>
		 */
		java.lang.String getPersonName();

		/**
		 * <code>optional string person_name = 7;</code>
		 *
		 * <pre>
		 * 人员名称
		 * </pre>
		 */
		com.google.protobuf.ByteString getPersonNameBytes();

		/**
		 * <code>optional int32 dept_id = 8;</code>
		 *
		 * <pre>
		 * 部门Id
		 * </pre>
		 */
		boolean hasDeptId();

		/**
		 * <code>optional int32 dept_id = 8;</code>
		 *
		 * <pre>
		 * 部门Id
		 * </pre>
		 */
		int getDeptId();

		/**
		 * <code>optional string dept_name = 9;</code>
		 *
		 * <pre>
		 * 部门名称
		 * </pre>
		 */
		boolean hasDeptName();

		/**
		 * <code>optional string dept_name = 9;</code>
		 *
		 * <pre>
		 * 部门名称
		 * </pre>
		 */
		java.lang.String getDeptName();

		/**
		 * <code>optional string dept_name = 9;</code>
		 *
		 * <pre>
		 * 部门名称
		 * </pre>
		 */
		com.google.protobuf.ByteString getDeptNameBytes();

		/**
		 * <code>optional string dept_code = 10;</code>
		 *
		 * <pre>
		 * 部门编码
		 * </pre>
		 */
		boolean hasDeptCode();

		/**
		 * <code>optional string dept_code = 10;</code>
		 *
		 * <pre>
		 * 部门编码
		 * </pre>
		 */
		java.lang.String getDeptCode();

		/**
		 * <code>optional string dept_code = 10;</code>
		 *
		 * <pre>
		 * 部门编码
		 * </pre>
		 */
		com.google.protobuf.ByteString getDeptCodeBytes();

		/**
		 * <code>optional int32 deviceL1_id = 11;</code>
		 *
		 * <pre>
		 * 一级设备Id
		 * </pre>
		 */
		boolean hasDeviceL1Id();

		/**
		 * <code>optional int32 deviceL1_id = 11;</code>
		 *
		 * <pre>
		 * 一级设备Id
		 * </pre>
		 */
		int getDeviceL1Id();

		/**
		 * <code>optional int32 deviceL1_type = 12;</code>
		 *
		 * <pre>
		 * 一级设备类型
		 * </pre>
		 */
		boolean hasDeviceL1Type();

		/**
		 * <code>optional int32 deviceL1_type = 12;</code>
		 *
		 * <pre>
		 * 一级设备类型
		 * </pre>
		 */
		int getDeviceL1Type();

		/**
		 * <code>optional string deviceL1_name = 13;</code>
		 *
		 * <pre>
		 * 一级设备名称
		 * </pre>
		 */
		boolean hasDeviceL1Name();

		/**
		 * <code>optional string deviceL1_name = 13;</code>
		 *
		 * <pre>
		 * 一级设备名称
		 * </pre>
		 */
		java.lang.String getDeviceL1Name();

		/**
		 * <code>optional string deviceL1_name = 13;</code>
		 *
		 * <pre>
		 * 一级设备名称
		 * </pre>
		 */
		com.google.protobuf.ByteString getDeviceL1NameBytes();

		/**
		 * <code>optional int32 deviceL2_id = 14;</code>
		 *
		 * <pre>
		 * 二级设备Id
		 * </pre>
		 */
		boolean hasDeviceL2Id();

		/**
		 * <code>optional int32 deviceL2_id = 14;</code>
		 *
		 * <pre>
		 * 二级设备Id
		 * </pre>
		 */
		int getDeviceL2Id();

		/**
		 * <code>optional int32 deviceL2_type = 15;</code>
		 *
		 * <pre>
		 * 二级设备类型
		 * </pre>
		 */
		boolean hasDeviceL2Type();

		/**
		 * <code>optional int32 deviceL2_type = 15;</code>
		 *
		 * <pre>
		 * 二级设备类型
		 * </pre>
		 */
		int getDeviceL2Type();

		/**
		 * <code>optional string deviceL2_name = 16;</code>
		 *
		 * <pre>
		 * 二级设备名称
		 * </pre>
		 */
		boolean hasDeviceL2Name();

		/**
		 * <code>optional string deviceL2_name = 16;</code>
		 *
		 * <pre>
		 * 二级设备名称
		 * </pre>
		 */
		java.lang.String getDeviceL2Name();

		/**
		 * <code>optional string deviceL2_name = 16;</code>
		 *
		 * <pre>
		 * 二级设备名称
		 * </pre>
		 */
		com.google.protobuf.ByteString getDeviceL2NameBytes();

		/**
		 * <code>optional int32 deviceL3_id = 17;</code>
		 *
		 * <pre>
		 * 三级设备Id
		 * </pre>
		 */
		boolean hasDeviceL3Id();

		/**
		 * <code>optional int32 deviceL3_id = 17;</code>
		 *
		 * <pre>
		 * 三级设备Id
		 * </pre>
		 */
		int getDeviceL3Id();

		/**
		 * <code>optional int32 deviceL3_type = 18;</code>
		 *
		 * <pre>
		 * 三级设备类型
		 * </pre>
		 */
		boolean hasDeviceL3Type();

		/**
		 * <code>optional int32 deviceL3_type = 18;</code>
		 *
		 * <pre>
		 * 三级设备类型
		 * </pre>
		 */
		int getDeviceL3Type();

		/**
		 * <code>optional string deviceL3_name = 19;</code>
		 *
		 * <pre>
		 * 三级设备名称
		 * </pre>
		 */
		boolean hasDeviceL3Name();

		/**
		 * <code>optional string deviceL3_name = 19;</code>
		 *
		 * <pre>
		 * 三级设备名称
		 * </pre>
		 */
		java.lang.String getDeviceL3Name();

		/**
		 * <code>optional string deviceL3_name = 19;</code>
		 *
		 * <pre>
		 * 三级设备名称
		 * </pre>
		 */
		com.google.protobuf.ByteString getDeviceL3NameBytes();

		/**
		 * <code>optional int32 in_out = 20;</code>
		 *
		 * <pre>
		 * 进出方向
		 * </pre>
		 */
		boolean hasInOut();

		/**
		 * <code>optional int32 in_out = 20;</code>
		 *
		 * <pre>
		 * 进出方向
		 * </pre>
		 */
		int getInOut();

		/**
		 * <code>optional string ext_txt = 21;</code>
		 *
		 * <pre>
		 * DAG上报的扩展信息内容，xml
		 * </pre>
		 */
		boolean hasExtTxt();

		/**
		 * <code>optional string ext_txt = 21;</code>
		 *
		 * <pre>
		 * DAG上报的扩展信息内容，xml
		 * </pre>
		 */
		java.lang.String getExtTxt();

		/**
		 * <code>optional string ext_txt = 21;</code>
		 *
		 * <pre>
		 * DAG上报的扩展信息内容，xml
		 * </pre>
		 */
		com.google.protobuf.ByteString getExtTxtBytes();

		/**
		 * <code>optional int32 door_id = 33;</code>
		 *
		 * <pre>
		 * 门Id
		 * </pre>
		 */
		boolean hasDoorId();

		/**
		 * <code>optional int32 door_id = 33;</code>
		 *
		 * <pre>
		 * 门Id
		 * </pre>
		 */
		int getDoorId();

		/**
		 * <code>optional int32 card_status = 34;</code>
		 *
		 * <pre>
		 * 卡状态
		 * </pre>
		 */
		boolean hasCardStatus();

		/**
		 * <code>optional int32 card_status = 34;</code>
		 *
		 * <pre>
		 * 卡状态
		 * </pre>
		 */
		int getCardStatus();

		/**
		 * <code>optional string pic_url = 35;</code>
		 *
		 * <pre>
		 * 图片url
		 * </pre>
		 */
		boolean hasPicUrl();

		/**
		 * <code>optional string pic_url = 35;</code>
		 *
		 * <pre>
		 * 图片url
		 * </pre>
		 */
		java.lang.String getPicUrl();

		/**
		 * <code>optional string pic_url = 35;</code>
		 *
		 * <pre>
		 * 图片url
		 * </pre>
		 */
		com.google.protobuf.ByteString getPicUrlBytes();
	}

	/**
	 * Protobuf type {@code net.zdsoft.officework.mqreceive.AccessEventLog}
	 *
	 * <pre>
	 * &#64;门禁事件日志消息结构体
	 * </pre>
	 */
	public static final class AccessEventLog extends
			com.google.protobuf.GeneratedMessage implements
	// @@protoc_insertion_point(message_implements:net.zdsoft.officework.mqreceive.AccessEventLog)
			AccessEventLogOrBuilder {
		// Use AccessEventLog.newBuilder() to construct.
		private AccessEventLog(
				com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private AccessEventLog(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final AccessEventLog defaultInstance;

		public static AccessEventLog getDefaultInstance() {
			return defaultInstance;
		}

		public AccessEventLog getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private AccessEventLog(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						eventCode_ = input.readInt32();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						deviceId_ = input.readInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						deviceType_ = input.readInt32();
						break;
					}
					case 34: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000008;
						deviceName_ = bs;
						break;
					}
					case 42: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000010;
						eventCard_ = bs;
						break;
					}
					case 48: {
						bitField0_ |= 0x00000020;
						personId_ = input.readInt32();
						break;
					}
					case 58: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000040;
						personName_ = bs;
						break;
					}
					case 64: {
						bitField0_ |= 0x00000080;
						deptId_ = input.readInt32();
						break;
					}
					case 74: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000100;
						deptName_ = bs;
						break;
					}
					case 82: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000200;
						deptCode_ = bs;
						break;
					}
					case 88: {
						bitField0_ |= 0x00000400;
						deviceL1Id_ = input.readInt32();
						break;
					}
					case 96: {
						bitField0_ |= 0x00000800;
						deviceL1Type_ = input.readInt32();
						break;
					}
					case 106: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00001000;
						deviceL1Name_ = bs;
						break;
					}
					case 112: {
						bitField0_ |= 0x00002000;
						deviceL2Id_ = input.readInt32();
						break;
					}
					case 120: {
						bitField0_ |= 0x00004000;
						deviceL2Type_ = input.readInt32();
						break;
					}
					case 130: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00008000;
						deviceL2Name_ = bs;
						break;
					}
					case 136: {
						bitField0_ |= 0x00010000;
						deviceL3Id_ = input.readInt32();
						break;
					}
					case 144: {
						bitField0_ |= 0x00020000;
						deviceL3Type_ = input.readInt32();
						break;
					}
					case 154: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00040000;
						deviceL3Name_ = bs;
						break;
					}
					case 160: {
						bitField0_ |= 0x00080000;
						inOut_ = input.readInt32();
						break;
					}
					case 170: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00100000;
						extTxt_ = bs;
						break;
					}
					case 264: {
						bitField0_ |= 0x00200000;
						doorId_ = input.readInt32();
						break;
					}
					case 272: {
						bitField0_ |= 0x00400000;
						cardStatus_ = input.readInt32();
						break;
					}
					case 282: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00800000;
						picUrl_ = bs;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.zdsoft.officework.mqreceive.AcsEvent.internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.zdsoft.officework.mqreceive.AcsEvent.internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog.class,
							net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog.Builder.class);
		}

		public static com.google.protobuf.Parser<AccessEventLog> PARSER = new com.google.protobuf.AbstractParser<AccessEventLog>() {
			public AccessEventLog parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new AccessEventLog(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<AccessEventLog> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		public static final int EVENT_CODE_FIELD_NUMBER = 1;
		private int eventCode_;

		/**
		 * <code>optional int32 event_code = 1;</code>
		 *
		 * <pre>
		 * 事件码，门禁原始定义事件码
		 * </pre>
		 */
		public boolean hasEventCode() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>optional int32 event_code = 1;</code>
		 *
		 * <pre>
		 * 事件码，门禁原始定义事件码
		 * </pre>
		 */
		public int getEventCode() {
			return eventCode_;
		}

		public static final int DEVICE_ID_FIELD_NUMBER = 2;
		private int deviceId_;

		/**
		 * <code>optional int32 device_id = 2;</code>
		 *
		 * <pre>
		 * 产生事件的设备Id，门禁刷卡事件就是读卡器Id
		 * </pre>
		 */
		public boolean hasDeviceId() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional int32 device_id = 2;</code>
		 *
		 * <pre>
		 * 产生事件的设备Id，门禁刷卡事件就是读卡器Id
		 * </pre>
		 */
		public int getDeviceId() {
			return deviceId_;
		}

		public static final int DEVICE_TYPE_FIELD_NUMBER = 3;
		private int deviceType_;

		/**
		 * <code>optional int32 device_type = 3;</code>
		 *
		 * <pre>
		 * 产生事件的设备类型
		 * </pre>
		 */
		public boolean hasDeviceType() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional int32 device_type = 3;</code>
		 *
		 * <pre>
		 * 产生事件的设备类型
		 * </pre>
		 */
		public int getDeviceType() {
			return deviceType_;
		}

		public static final int DEVICE_NAME_FIELD_NUMBER = 4;
		private java.lang.Object deviceName_;

		/**
		 * <code>optional string device_name = 4;</code>
		 *
		 * <pre>
		 * 产生事件的设备名称
		 * </pre>
		 */
		public boolean hasDeviceName() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>optional string device_name = 4;</code>
		 *
		 * <pre>
		 * 产生事件的设备名称
		 * </pre>
		 */
		public java.lang.String getDeviceName() {
			java.lang.Object ref = deviceName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					deviceName_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string device_name = 4;</code>
		 *
		 * <pre>
		 * 产生事件的设备名称
		 * </pre>
		 */
		public com.google.protobuf.ByteString getDeviceNameBytes() {
			java.lang.Object ref = deviceName_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				deviceName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int EVENT_CARD_FIELD_NUMBER = 5;
		private java.lang.Object eventCard_;

		/**
		 * <code>optional string event_card = 5;</code>
		 *
		 * <pre>
		 * 卡号
		 * </pre>
		 */
		public boolean hasEventCard() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		/**
		 * <code>optional string event_card = 5;</code>
		 *
		 * <pre>
		 * 卡号
		 * </pre>
		 */
		public java.lang.String getEventCard() {
			java.lang.Object ref = eventCard_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					eventCard_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string event_card = 5;</code>
		 *
		 * <pre>
		 * 卡号
		 * </pre>
		 */
		public com.google.protobuf.ByteString getEventCardBytes() {
			java.lang.Object ref = eventCard_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				eventCard_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PERSON_ID_FIELD_NUMBER = 6;
		private int personId_;

		/**
		 * <code>optional int32 person_id = 6;</code>
		 *
		 * <pre>
		 * 人员Id
		 * </pre>
		 */
		public boolean hasPersonId() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}

		/**
		 * <code>optional int32 person_id = 6;</code>
		 *
		 * <pre>
		 * 人员Id
		 * </pre>
		 */
		public int getPersonId() {
			return personId_;
		}

		public static final int PERSON_NAME_FIELD_NUMBER = 7;
		private java.lang.Object personName_;

		/**
		 * <code>optional string person_name = 7;</code>
		 *
		 * <pre>
		 * 人员名称
		 * </pre>
		 */
		public boolean hasPersonName() {
			return ((bitField0_ & 0x00000040) == 0x00000040);
		}

		/**
		 * <code>optional string person_name = 7;</code>
		 *
		 * <pre>
		 * 人员名称
		 * </pre>
		 */
		public java.lang.String getPersonName() {
			java.lang.Object ref = personName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					personName_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string person_name = 7;</code>
		 *
		 * <pre>
		 * 人员名称
		 * </pre>
		 */
		public com.google.protobuf.ByteString getPersonNameBytes() {
			java.lang.Object ref = personName_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				personName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DEPT_ID_FIELD_NUMBER = 8;
		private int deptId_;

		/**
		 * <code>optional int32 dept_id = 8;</code>
		 *
		 * <pre>
		 * 部门Id
		 * </pre>
		 */
		public boolean hasDeptId() {
			return ((bitField0_ & 0x00000080) == 0x00000080);
		}

		/**
		 * <code>optional int32 dept_id = 8;</code>
		 *
		 * <pre>
		 * 部门Id
		 * </pre>
		 */
		public int getDeptId() {
			return deptId_;
		}

		public static final int DEPT_NAME_FIELD_NUMBER = 9;
		private java.lang.Object deptName_;

		/**
		 * <code>optional string dept_name = 9;</code>
		 *
		 * <pre>
		 * 部门名称
		 * </pre>
		 */
		public boolean hasDeptName() {
			return ((bitField0_ & 0x00000100) == 0x00000100);
		}

		/**
		 * <code>optional string dept_name = 9;</code>
		 *
		 * <pre>
		 * 部门名称
		 * </pre>
		 */
		public java.lang.String getDeptName() {
			java.lang.Object ref = deptName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					deptName_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string dept_name = 9;</code>
		 *
		 * <pre>
		 * 部门名称
		 * </pre>
		 */
		public com.google.protobuf.ByteString getDeptNameBytes() {
			java.lang.Object ref = deptName_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				deptName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DEPT_CODE_FIELD_NUMBER = 10;
		private java.lang.Object deptCode_;

		/**
		 * <code>optional string dept_code = 10;</code>
		 *
		 * <pre>
		 * 部门编码
		 * </pre>
		 */
		public boolean hasDeptCode() {
			return ((bitField0_ & 0x00000200) == 0x00000200);
		}

		/**
		 * <code>optional string dept_code = 10;</code>
		 *
		 * <pre>
		 * 部门编码
		 * </pre>
		 */
		public java.lang.String getDeptCode() {
			java.lang.Object ref = deptCode_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					deptCode_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string dept_code = 10;</code>
		 *
		 * <pre>
		 * 部门编码
		 * </pre>
		 */
		public com.google.protobuf.ByteString getDeptCodeBytes() {
			java.lang.Object ref = deptCode_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				deptCode_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DEVICEL1_ID_FIELD_NUMBER = 11;
		private int deviceL1Id_;

		/**
		 * <code>optional int32 deviceL1_id = 11;</code>
		 *
		 * <pre>
		 * 一级设备Id
		 * </pre>
		 */
		public boolean hasDeviceL1Id() {
			return ((bitField0_ & 0x00000400) == 0x00000400);
		}

		/**
		 * <code>optional int32 deviceL1_id = 11;</code>
		 *
		 * <pre>
		 * 一级设备Id
		 * </pre>
		 */
		public int getDeviceL1Id() {
			return deviceL1Id_;
		}

		public static final int DEVICEL1_TYPE_FIELD_NUMBER = 12;
		private int deviceL1Type_;

		/**
		 * <code>optional int32 deviceL1_type = 12;</code>
		 *
		 * <pre>
		 * 一级设备类型
		 * </pre>
		 */
		public boolean hasDeviceL1Type() {
			return ((bitField0_ & 0x00000800) == 0x00000800);
		}

		/**
		 * <code>optional int32 deviceL1_type = 12;</code>
		 *
		 * <pre>
		 * 一级设备类型
		 * </pre>
		 */
		public int getDeviceL1Type() {
			return deviceL1Type_;
		}

		public static final int DEVICEL1_NAME_FIELD_NUMBER = 13;
		private java.lang.Object deviceL1Name_;

		/**
		 * <code>optional string deviceL1_name = 13;</code>
		 *
		 * <pre>
		 * 一级设备名称
		 * </pre>
		 */
		public boolean hasDeviceL1Name() {
			return ((bitField0_ & 0x00001000) == 0x00001000);
		}

		/**
		 * <code>optional string deviceL1_name = 13;</code>
		 *
		 * <pre>
		 * 一级设备名称
		 * </pre>
		 */
		public java.lang.String getDeviceL1Name() {
			java.lang.Object ref = deviceL1Name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					deviceL1Name_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string deviceL1_name = 13;</code>
		 *
		 * <pre>
		 * 一级设备名称
		 * </pre>
		 */
		public com.google.protobuf.ByteString getDeviceL1NameBytes() {
			java.lang.Object ref = deviceL1Name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				deviceL1Name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DEVICEL2_ID_FIELD_NUMBER = 14;
		private int deviceL2Id_;

		/**
		 * <code>optional int32 deviceL2_id = 14;</code>
		 *
		 * <pre>
		 * 二级设备Id
		 * </pre>
		 */
		public boolean hasDeviceL2Id() {
			return ((bitField0_ & 0x00002000) == 0x00002000);
		}

		/**
		 * <code>optional int32 deviceL2_id = 14;</code>
		 *
		 * <pre>
		 * 二级设备Id
		 * </pre>
		 */
		public int getDeviceL2Id() {
			return deviceL2Id_;
		}

		public static final int DEVICEL2_TYPE_FIELD_NUMBER = 15;
		private int deviceL2Type_;

		/**
		 * <code>optional int32 deviceL2_type = 15;</code>
		 *
		 * <pre>
		 * 二级设备类型
		 * </pre>
		 */
		public boolean hasDeviceL2Type() {
			return ((bitField0_ & 0x00004000) == 0x00004000);
		}

		/**
		 * <code>optional int32 deviceL2_type = 15;</code>
		 *
		 * <pre>
		 * 二级设备类型
		 * </pre>
		 */
		public int getDeviceL2Type() {
			return deviceL2Type_;
		}

		public static final int DEVICEL2_NAME_FIELD_NUMBER = 16;
		private java.lang.Object deviceL2Name_;

		/**
		 * <code>optional string deviceL2_name = 16;</code>
		 *
		 * <pre>
		 * 二级设备名称
		 * </pre>
		 */
		public boolean hasDeviceL2Name() {
			return ((bitField0_ & 0x00008000) == 0x00008000);
		}

		/**
		 * <code>optional string deviceL2_name = 16;</code>
		 *
		 * <pre>
		 * 二级设备名称
		 * </pre>
		 */
		public java.lang.String getDeviceL2Name() {
			java.lang.Object ref = deviceL2Name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					deviceL2Name_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string deviceL2_name = 16;</code>
		 *
		 * <pre>
		 * 二级设备名称
		 * </pre>
		 */
		public com.google.protobuf.ByteString getDeviceL2NameBytes() {
			java.lang.Object ref = deviceL2Name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				deviceL2Name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DEVICEL3_ID_FIELD_NUMBER = 17;
		private int deviceL3Id_;

		/**
		 * <code>optional int32 deviceL3_id = 17;</code>
		 *
		 * <pre>
		 * 三级设备Id
		 * </pre>
		 */
		public boolean hasDeviceL3Id() {
			return ((bitField0_ & 0x00010000) == 0x00010000);
		}

		/**
		 * <code>optional int32 deviceL3_id = 17;</code>
		 *
		 * <pre>
		 * 三级设备Id
		 * </pre>
		 */
		public int getDeviceL3Id() {
			return deviceL3Id_;
		}

		public static final int DEVICEL3_TYPE_FIELD_NUMBER = 18;
		private int deviceL3Type_;

		/**
		 * <code>optional int32 deviceL3_type = 18;</code>
		 *
		 * <pre>
		 * 三级设备类型
		 * </pre>
		 */
		public boolean hasDeviceL3Type() {
			return ((bitField0_ & 0x00020000) == 0x00020000);
		}

		/**
		 * <code>optional int32 deviceL3_type = 18;</code>
		 *
		 * <pre>
		 * 三级设备类型
		 * </pre>
		 */
		public int getDeviceL3Type() {
			return deviceL3Type_;
		}

		public static final int DEVICEL3_NAME_FIELD_NUMBER = 19;
		private java.lang.Object deviceL3Name_;

		/**
		 * <code>optional string deviceL3_name = 19;</code>
		 *
		 * <pre>
		 * 三级设备名称
		 * </pre>
		 */
		public boolean hasDeviceL3Name() {
			return ((bitField0_ & 0x00040000) == 0x00040000);
		}

		/**
		 * <code>optional string deviceL3_name = 19;</code>
		 *
		 * <pre>
		 * 三级设备名称
		 * </pre>
		 */
		public java.lang.String getDeviceL3Name() {
			java.lang.Object ref = deviceL3Name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					deviceL3Name_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string deviceL3_name = 19;</code>
		 *
		 * <pre>
		 * 三级设备名称
		 * </pre>
		 */
		public com.google.protobuf.ByteString getDeviceL3NameBytes() {
			java.lang.Object ref = deviceL3Name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				deviceL3Name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int IN_OUT_FIELD_NUMBER = 20;
		private int inOut_;

		/**
		 * <code>optional int32 in_out = 20;</code>
		 *
		 * <pre>
		 * 进出方向
		 * </pre>
		 */
		public boolean hasInOut() {
			return ((bitField0_ & 0x00080000) == 0x00080000);
		}

		/**
		 * <code>optional int32 in_out = 20;</code>
		 *
		 * <pre>
		 * 进出方向
		 * </pre>
		 */
		public int getInOut() {
			return inOut_;
		}

		public static final int EXT_TXT_FIELD_NUMBER = 21;
		private java.lang.Object extTxt_;

		/**
		 * <code>optional string ext_txt = 21;</code>
		 *
		 * <pre>
		 * DAG上报的扩展信息内容，xml
		 * </pre>
		 */
		public boolean hasExtTxt() {
			return ((bitField0_ & 0x00100000) == 0x00100000);
		}

		/**
		 * <code>optional string ext_txt = 21;</code>
		 *
		 * <pre>
		 * DAG上报的扩展信息内容，xml
		 * </pre>
		 */
		public java.lang.String getExtTxt() {
			java.lang.Object ref = extTxt_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					extTxt_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string ext_txt = 21;</code>
		 *
		 * <pre>
		 * DAG上报的扩展信息内容，xml
		 * </pre>
		 */
		public com.google.protobuf.ByteString getExtTxtBytes() {
			java.lang.Object ref = extTxt_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				extTxt_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DOOR_ID_FIELD_NUMBER = 33;
		private int doorId_;

		/**
		 * <code>optional int32 door_id = 33;</code>
		 *
		 * <pre>
		 * 门Id
		 * </pre>
		 */
		public boolean hasDoorId() {
			return ((bitField0_ & 0x00200000) == 0x00200000);
		}

		/**
		 * <code>optional int32 door_id = 33;</code>
		 *
		 * <pre>
		 * 门Id
		 * </pre>
		 */
		public int getDoorId() {
			return doorId_;
		}

		public static final int CARD_STATUS_FIELD_NUMBER = 34;
		private int cardStatus_;

		/**
		 * <code>optional int32 card_status = 34;</code>
		 *
		 * <pre>
		 * 卡状态
		 * </pre>
		 */
		public boolean hasCardStatus() {
			return ((bitField0_ & 0x00400000) == 0x00400000);
		}

		/**
		 * <code>optional int32 card_status = 34;</code>
		 *
		 * <pre>
		 * 卡状态
		 * </pre>
		 */
		public int getCardStatus() {
			return cardStatus_;
		}

		public static final int PIC_URL_FIELD_NUMBER = 35;
		private java.lang.Object picUrl_;

		/**
		 * <code>optional string pic_url = 35;</code>
		 *
		 * <pre>
		 * 图片url
		 * </pre>
		 */
		public boolean hasPicUrl() {
			return ((bitField0_ & 0x00800000) == 0x00800000);
		}

		/**
		 * <code>optional string pic_url = 35;</code>
		 *
		 * <pre>
		 * 图片url
		 * </pre>
		 */
		public java.lang.String getPicUrl() {
			java.lang.Object ref = picUrl_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					picUrl_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string pic_url = 35;</code>
		 *
		 * <pre>
		 * 图片url
		 * </pre>
		 */
		public com.google.protobuf.ByteString getPicUrlBytes() {
			java.lang.Object ref = picUrl_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				picUrl_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			eventCode_ = 0;
			deviceId_ = 0;
			deviceType_ = 0;
			deviceName_ = "";
			eventCard_ = "";
			personId_ = 0;
			personName_ = "";
			deptId_ = 0;
			deptName_ = "";
			deptCode_ = "";
			deviceL1Id_ = 0;
			deviceL1Type_ = 0;
			deviceL1Name_ = "";
			deviceL2Id_ = 0;
			deviceL2Type_ = 0;
			deviceL2Name_ = "";
			deviceL3Id_ = 0;
			deviceL3Type_ = 0;
			deviceL3Name_ = "";
			inOut_ = 0;
			extTxt_ = "";
			doorId_ = 0;
			cardStatus_ = 0;
			picUrl_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, eventCode_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, deviceId_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, deviceType_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(4, getDeviceNameBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(5, getEventCardBytes());
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeInt32(6, personId_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				output.writeBytes(7, getPersonNameBytes());
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				output.writeInt32(8, deptId_);
			}
			if (((bitField0_ & 0x00000100) == 0x00000100)) {
				output.writeBytes(9, getDeptNameBytes());
			}
			if (((bitField0_ & 0x00000200) == 0x00000200)) {
				output.writeBytes(10, getDeptCodeBytes());
			}
			if (((bitField0_ & 0x00000400) == 0x00000400)) {
				output.writeInt32(11, deviceL1Id_);
			}
			if (((bitField0_ & 0x00000800) == 0x00000800)) {
				output.writeInt32(12, deviceL1Type_);
			}
			if (((bitField0_ & 0x00001000) == 0x00001000)) {
				output.writeBytes(13, getDeviceL1NameBytes());
			}
			if (((bitField0_ & 0x00002000) == 0x00002000)) {
				output.writeInt32(14, deviceL2Id_);
			}
			if (((bitField0_ & 0x00004000) == 0x00004000)) {
				output.writeInt32(15, deviceL2Type_);
			}
			if (((bitField0_ & 0x00008000) == 0x00008000)) {
				output.writeBytes(16, getDeviceL2NameBytes());
			}
			if (((bitField0_ & 0x00010000) == 0x00010000)) {
				output.writeInt32(17, deviceL3Id_);
			}
			if (((bitField0_ & 0x00020000) == 0x00020000)) {
				output.writeInt32(18, deviceL3Type_);
			}
			if (((bitField0_ & 0x00040000) == 0x00040000)) {
				output.writeBytes(19, getDeviceL3NameBytes());
			}
			if (((bitField0_ & 0x00080000) == 0x00080000)) {
				output.writeInt32(20, inOut_);
			}
			if (((bitField0_ & 0x00100000) == 0x00100000)) {
				output.writeBytes(21, getExtTxtBytes());
			}
			if (((bitField0_ & 0x00200000) == 0x00200000)) {
				output.writeInt32(33, doorId_);
			}
			if (((bitField0_ & 0x00400000) == 0x00400000)) {
				output.writeInt32(34, cardStatus_);
			}
			if (((bitField0_ & 0x00800000) == 0x00800000)) {
				output.writeBytes(35, getPicUrlBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, eventCode_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						2, deviceId_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, deviceType_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						4, getDeviceNameBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						5, getEventCardBytes());
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						6, personId_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						7, getPersonNameBytes());
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						8, deptId_);
			}
			if (((bitField0_ & 0x00000100) == 0x00000100)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						9, getDeptNameBytes());
			}
			if (((bitField0_ & 0x00000200) == 0x00000200)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						10, getDeptCodeBytes());
			}
			if (((bitField0_ & 0x00000400) == 0x00000400)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						11, deviceL1Id_);
			}
			if (((bitField0_ & 0x00000800) == 0x00000800)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						12, deviceL1Type_);
			}
			if (((bitField0_ & 0x00001000) == 0x00001000)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						13, getDeviceL1NameBytes());
			}
			if (((bitField0_ & 0x00002000) == 0x00002000)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						14, deviceL2Id_);
			}
			if (((bitField0_ & 0x00004000) == 0x00004000)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						15, deviceL2Type_);
			}
			if (((bitField0_ & 0x00008000) == 0x00008000)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						16, getDeviceL2NameBytes());
			}
			if (((bitField0_ & 0x00010000) == 0x00010000)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						17, deviceL3Id_);
			}
			if (((bitField0_ & 0x00020000) == 0x00020000)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						18, deviceL3Type_);
			}
			if (((bitField0_ & 0x00040000) == 0x00040000)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						19, getDeviceL3NameBytes());
			}
			if (((bitField0_ & 0x00080000) == 0x00080000)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						20, inOut_);
			}
			if (((bitField0_ & 0x00100000) == 0x00100000)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						21, getExtTxtBytes());
			}
			if (((bitField0_ & 0x00200000) == 0x00200000)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						33, doorId_);
			}
			if (((bitField0_ & 0x00400000) == 0x00400000)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						34, cardStatus_);
			}
			if (((bitField0_ & 0x00800000) == 0x00800000)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						35, getPicUrlBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code net.zdsoft.officework.mqreceive.AccessEventLog}
		 *
		 * <pre>
		 * &#64;门禁事件日志消息结构体
		 * </pre>
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				// @@protoc_insertion_point(builder_implements:net.zdsoft.officework.mqreceive.AccessEventLog)
				net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLogOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return net.zdsoft.officework.mqreceive.AcsEvent.internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return net.zdsoft.officework.mqreceive.AcsEvent.internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog.class,
								net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog.Builder.class);
			}

			// Construct using
			// net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				eventCode_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				deviceId_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				deviceType_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				deviceName_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				eventCard_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				personId_ = 0;
				bitField0_ = (bitField0_ & ~0x00000020);
				personName_ = "";
				bitField0_ = (bitField0_ & ~0x00000040);
				deptId_ = 0;
				bitField0_ = (bitField0_ & ~0x00000080);
				deptName_ = "";
				bitField0_ = (bitField0_ & ~0x00000100);
				deptCode_ = "";
				bitField0_ = (bitField0_ & ~0x00000200);
				deviceL1Id_ = 0;
				bitField0_ = (bitField0_ & ~0x00000400);
				deviceL1Type_ = 0;
				bitField0_ = (bitField0_ & ~0x00000800);
				deviceL1Name_ = "";
				bitField0_ = (bitField0_ & ~0x00001000);
				deviceL2Id_ = 0;
				bitField0_ = (bitField0_ & ~0x00002000);
				deviceL2Type_ = 0;
				bitField0_ = (bitField0_ & ~0x00004000);
				deviceL2Name_ = "";
				bitField0_ = (bitField0_ & ~0x00008000);
				deviceL3Id_ = 0;
				bitField0_ = (bitField0_ & ~0x00010000);
				deviceL3Type_ = 0;
				bitField0_ = (bitField0_ & ~0x00020000);
				deviceL3Name_ = "";
				bitField0_ = (bitField0_ & ~0x00040000);
				inOut_ = 0;
				bitField0_ = (bitField0_ & ~0x00080000);
				extTxt_ = "";
				bitField0_ = (bitField0_ & ~0x00100000);
				doorId_ = 0;
				bitField0_ = (bitField0_ & ~0x00200000);
				cardStatus_ = 0;
				bitField0_ = (bitField0_ & ~0x00400000);
				picUrl_ = "";
				bitField0_ = (bitField0_ & ~0x00800000);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return net.zdsoft.officework.mqreceive.AcsEvent.internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_descriptor;
			}

			public net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog getDefaultInstanceForType() {
				return net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog
						.getDefaultInstance();
			}

			public net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog build() {
				net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog buildPartial() {
				net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog result = new net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.eventCode_ = eventCode_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.deviceId_ = deviceId_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.deviceType_ = deviceType_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.deviceName_ = deviceName_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.eventCard_ = eventCard_;
				if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
					to_bitField0_ |= 0x00000020;
				}
				result.personId_ = personId_;
				if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
					to_bitField0_ |= 0x00000040;
				}
				result.personName_ = personName_;
				if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
					to_bitField0_ |= 0x00000080;
				}
				result.deptId_ = deptId_;
				if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
					to_bitField0_ |= 0x00000100;
				}
				result.deptName_ = deptName_;
				if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
					to_bitField0_ |= 0x00000200;
				}
				result.deptCode_ = deptCode_;
				if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
					to_bitField0_ |= 0x00000400;
				}
				result.deviceL1Id_ = deviceL1Id_;
				if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
					to_bitField0_ |= 0x00000800;
				}
				result.deviceL1Type_ = deviceL1Type_;
				if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
					to_bitField0_ |= 0x00001000;
				}
				result.deviceL1Name_ = deviceL1Name_;
				if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
					to_bitField0_ |= 0x00002000;
				}
				result.deviceL2Id_ = deviceL2Id_;
				if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
					to_bitField0_ |= 0x00004000;
				}
				result.deviceL2Type_ = deviceL2Type_;
				if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
					to_bitField0_ |= 0x00008000;
				}
				result.deviceL2Name_ = deviceL2Name_;
				if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
					to_bitField0_ |= 0x00010000;
				}
				result.deviceL3Id_ = deviceL3Id_;
				if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
					to_bitField0_ |= 0x00020000;
				}
				result.deviceL3Type_ = deviceL3Type_;
				if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
					to_bitField0_ |= 0x00040000;
				}
				result.deviceL3Name_ = deviceL3Name_;
				if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
					to_bitField0_ |= 0x00080000;
				}
				result.inOut_ = inOut_;
				if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
					to_bitField0_ |= 0x00100000;
				}
				result.extTxt_ = extTxt_;
				if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
					to_bitField0_ |= 0x00200000;
				}
				result.doorId_ = doorId_;
				if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
					to_bitField0_ |= 0x00400000;
				}
				result.cardStatus_ = cardStatus_;
				if (((from_bitField0_ & 0x00800000) == 0x00800000)) {
					to_bitField0_ |= 0x00800000;
				}
				result.picUrl_ = picUrl_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog) {
					return mergeFrom((net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog other) {
				if (other == net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog
						.getDefaultInstance())
					return this;
				if (other.hasEventCode()) {
					setEventCode(other.getEventCode());
				}
				if (other.hasDeviceId()) {
					setDeviceId(other.getDeviceId());
				}
				if (other.hasDeviceType()) {
					setDeviceType(other.getDeviceType());
				}
				if (other.hasDeviceName()) {
					bitField0_ |= 0x00000008;
					deviceName_ = other.deviceName_;
					onChanged();
				}
				if (other.hasEventCard()) {
					bitField0_ |= 0x00000010;
					eventCard_ = other.eventCard_;
					onChanged();
				}
				if (other.hasPersonId()) {
					setPersonId(other.getPersonId());
				}
				if (other.hasPersonName()) {
					bitField0_ |= 0x00000040;
					personName_ = other.personName_;
					onChanged();
				}
				if (other.hasDeptId()) {
					setDeptId(other.getDeptId());
				}
				if (other.hasDeptName()) {
					bitField0_ |= 0x00000100;
					deptName_ = other.deptName_;
					onChanged();
				}
				if (other.hasDeptCode()) {
					bitField0_ |= 0x00000200;
					deptCode_ = other.deptCode_;
					onChanged();
				}
				if (other.hasDeviceL1Id()) {
					setDeviceL1Id(other.getDeviceL1Id());
				}
				if (other.hasDeviceL1Type()) {
					setDeviceL1Type(other.getDeviceL1Type());
				}
				if (other.hasDeviceL1Name()) {
					bitField0_ |= 0x00001000;
					deviceL1Name_ = other.deviceL1Name_;
					onChanged();
				}
				if (other.hasDeviceL2Id()) {
					setDeviceL2Id(other.getDeviceL2Id());
				}
				if (other.hasDeviceL2Type()) {
					setDeviceL2Type(other.getDeviceL2Type());
				}
				if (other.hasDeviceL2Name()) {
					bitField0_ |= 0x00008000;
					deviceL2Name_ = other.deviceL2Name_;
					onChanged();
				}
				if (other.hasDeviceL3Id()) {
					setDeviceL3Id(other.getDeviceL3Id());
				}
				if (other.hasDeviceL3Type()) {
					setDeviceL3Type(other.getDeviceL3Type());
				}
				if (other.hasDeviceL3Name()) {
					bitField0_ |= 0x00040000;
					deviceL3Name_ = other.deviceL3Name_;
					onChanged();
				}
				if (other.hasInOut()) {
					setInOut(other.getInOut());
				}
				if (other.hasExtTxt()) {
					bitField0_ |= 0x00100000;
					extTxt_ = other.extTxt_;
					onChanged();
				}
				if (other.hasDoorId()) {
					setDoorId(other.getDoorId());
				}
				if (other.hasCardStatus()) {
					setCardStatus(other.getCardStatus());
				}
				if (other.hasPicUrl()) {
					bitField0_ |= 0x00800000;
					picUrl_ = other.picUrl_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (net.zdsoft.officework.mqreceive.AcsEvent.AccessEventLog) e
							.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private int eventCode_;

			/**
			 * <code>optional int32 event_code = 1;</code>
			 *
			 * <pre>
			 * 事件码，门禁原始定义事件码
			 * </pre>
			 */
			public boolean hasEventCode() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>optional int32 event_code = 1;</code>
			 *
			 * <pre>
			 * 事件码，门禁原始定义事件码
			 * </pre>
			 */
			public int getEventCode() {
				return eventCode_;
			}

			/**
			 * <code>optional int32 event_code = 1;</code>
			 *
			 * <pre>
			 * 事件码，门禁原始定义事件码
			 * </pre>
			 */
			public Builder setEventCode(int value) {
				bitField0_ |= 0x00000001;
				eventCode_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 event_code = 1;</code>
			 *
			 * <pre>
			 * 事件码，门禁原始定义事件码
			 * </pre>
			 */
			public Builder clearEventCode() {
				bitField0_ = (bitField0_ & ~0x00000001);
				eventCode_ = 0;
				onChanged();
				return this;
			}

			private int deviceId_;

			/**
			 * <code>optional int32 device_id = 2;</code>
			 *
			 * <pre>
			 * 产生事件的设备Id，门禁刷卡事件就是读卡器Id
			 * </pre>
			 */
			public boolean hasDeviceId() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional int32 device_id = 2;</code>
			 *
			 * <pre>
			 * 产生事件的设备Id，门禁刷卡事件就是读卡器Id
			 * </pre>
			 */
			public int getDeviceId() {
				return deviceId_;
			}

			/**
			 * <code>optional int32 device_id = 2;</code>
			 *
			 * <pre>
			 * 产生事件的设备Id，门禁刷卡事件就是读卡器Id
			 * </pre>
			 */
			public Builder setDeviceId(int value) {
				bitField0_ |= 0x00000002;
				deviceId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 device_id = 2;</code>
			 *
			 * <pre>
			 * 产生事件的设备Id，门禁刷卡事件就是读卡器Id
			 * </pre>
			 */
			public Builder clearDeviceId() {
				bitField0_ = (bitField0_ & ~0x00000002);
				deviceId_ = 0;
				onChanged();
				return this;
			}

			private int deviceType_;

			/**
			 * <code>optional int32 device_type = 3;</code>
			 *
			 * <pre>
			 * 产生事件的设备类型
			 * </pre>
			 */
			public boolean hasDeviceType() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional int32 device_type = 3;</code>
			 *
			 * <pre>
			 * 产生事件的设备类型
			 * </pre>
			 */
			public int getDeviceType() {
				return deviceType_;
			}

			/**
			 * <code>optional int32 device_type = 3;</code>
			 *
			 * <pre>
			 * 产生事件的设备类型
			 * </pre>
			 */
			public Builder setDeviceType(int value) {
				bitField0_ |= 0x00000004;
				deviceType_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 device_type = 3;</code>
			 *
			 * <pre>
			 * 产生事件的设备类型
			 * </pre>
			 */
			public Builder clearDeviceType() {
				bitField0_ = (bitField0_ & ~0x00000004);
				deviceType_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object deviceName_ = "";

			/**
			 * <code>optional string device_name = 4;</code>
			 *
			 * <pre>
			 * 产生事件的设备名称
			 * </pre>
			 */
			public boolean hasDeviceName() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional string device_name = 4;</code>
			 *
			 * <pre>
			 * 产生事件的设备名称
			 * </pre>
			 */
			public java.lang.String getDeviceName() {
				java.lang.Object ref = deviceName_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						deviceName_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string device_name = 4;</code>
			 *
			 * <pre>
			 * 产生事件的设备名称
			 * </pre>
			 */
			public com.google.protobuf.ByteString getDeviceNameBytes() {
				java.lang.Object ref = deviceName_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					deviceName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string device_name = 4;</code>
			 *
			 * <pre>
			 * 产生事件的设备名称
			 * </pre>
			 */
			public Builder setDeviceName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				deviceName_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string device_name = 4;</code>
			 *
			 * <pre>
			 * 产生事件的设备名称
			 * </pre>
			 */
			public Builder clearDeviceName() {
				bitField0_ = (bitField0_ & ~0x00000008);
				deviceName_ = getDefaultInstance().getDeviceName();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string device_name = 4;</code>
			 *
			 * <pre>
			 * 产生事件的设备名称
			 * </pre>
			 */
			public Builder setDeviceNameBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				deviceName_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object eventCard_ = "";

			/**
			 * <code>optional string event_card = 5;</code>
			 *
			 * <pre>
			 * 卡号
			 * </pre>
			 */
			public boolean hasEventCard() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			/**
			 * <code>optional string event_card = 5;</code>
			 *
			 * <pre>
			 * 卡号
			 * </pre>
			 */
			public java.lang.String getEventCard() {
				java.lang.Object ref = eventCard_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						eventCard_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string event_card = 5;</code>
			 *
			 * <pre>
			 * 卡号
			 * </pre>
			 */
			public com.google.protobuf.ByteString getEventCardBytes() {
				java.lang.Object ref = eventCard_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					eventCard_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string event_card = 5;</code>
			 *
			 * <pre>
			 * 卡号
			 * </pre>
			 */
			public Builder setEventCard(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				eventCard_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string event_card = 5;</code>
			 *
			 * <pre>
			 * 卡号
			 * </pre>
			 */
			public Builder clearEventCard() {
				bitField0_ = (bitField0_ & ~0x00000010);
				eventCard_ = getDefaultInstance().getEventCard();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string event_card = 5;</code>
			 *
			 * <pre>
			 * 卡号
			 * </pre>
			 */
			public Builder setEventCardBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				eventCard_ = value;
				onChanged();
				return this;
			}

			private int personId_;

			/**
			 * <code>optional int32 person_id = 6;</code>
			 *
			 * <pre>
			 * 人员Id
			 * </pre>
			 */
			public boolean hasPersonId() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}

			/**
			 * <code>optional int32 person_id = 6;</code>
			 *
			 * <pre>
			 * 人员Id
			 * </pre>
			 */
			public int getPersonId() {
				return personId_;
			}

			/**
			 * <code>optional int32 person_id = 6;</code>
			 *
			 * <pre>
			 * 人员Id
			 * </pre>
			 */
			public Builder setPersonId(int value) {
				bitField0_ |= 0x00000020;
				personId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 person_id = 6;</code>
			 *
			 * <pre>
			 * 人员Id
			 * </pre>
			 */
			public Builder clearPersonId() {
				bitField0_ = (bitField0_ & ~0x00000020);
				personId_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object personName_ = "";

			/**
			 * <code>optional string person_name = 7;</code>
			 *
			 * <pre>
			 * 人员名称
			 * </pre>
			 */
			public boolean hasPersonName() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}

			/**
			 * <code>optional string person_name = 7;</code>
			 *
			 * <pre>
			 * 人员名称
			 * </pre>
			 */
			public java.lang.String getPersonName() {
				java.lang.Object ref = personName_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						personName_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string person_name = 7;</code>
			 *
			 * <pre>
			 * 人员名称
			 * </pre>
			 */
			public com.google.protobuf.ByteString getPersonNameBytes() {
				java.lang.Object ref = personName_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					personName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string person_name = 7;</code>
			 *
			 * <pre>
			 * 人员名称
			 * </pre>
			 */
			public Builder setPersonName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000040;
				personName_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string person_name = 7;</code>
			 *
			 * <pre>
			 * 人员名称
			 * </pre>
			 */
			public Builder clearPersonName() {
				bitField0_ = (bitField0_ & ~0x00000040);
				personName_ = getDefaultInstance().getPersonName();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string person_name = 7;</code>
			 *
			 * <pre>
			 * 人员名称
			 * </pre>
			 */
			public Builder setPersonNameBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000040;
				personName_ = value;
				onChanged();
				return this;
			}

			private int deptId_;

			/**
			 * <code>optional int32 dept_id = 8;</code>
			 *
			 * <pre>
			 * 部门Id
			 * </pre>
			 */
			public boolean hasDeptId() {
				return ((bitField0_ & 0x00000080) == 0x00000080);
			}

			/**
			 * <code>optional int32 dept_id = 8;</code>
			 *
			 * <pre>
			 * 部门Id
			 * </pre>
			 */
			public int getDeptId() {
				return deptId_;
			}

			/**
			 * <code>optional int32 dept_id = 8;</code>
			 *
			 * <pre>
			 * 部门Id
			 * </pre>
			 */
			public Builder setDeptId(int value) {
				bitField0_ |= 0x00000080;
				deptId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 dept_id = 8;</code>
			 *
			 * <pre>
			 * 部门Id
			 * </pre>
			 */
			public Builder clearDeptId() {
				bitField0_ = (bitField0_ & ~0x00000080);
				deptId_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object deptName_ = "";

			/**
			 * <code>optional string dept_name = 9;</code>
			 *
			 * <pre>
			 * 部门名称
			 * </pre>
			 */
			public boolean hasDeptName() {
				return ((bitField0_ & 0x00000100) == 0x00000100);
			}

			/**
			 * <code>optional string dept_name = 9;</code>
			 *
			 * <pre>
			 * 部门名称
			 * </pre>
			 */
			public java.lang.String getDeptName() {
				java.lang.Object ref = deptName_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						deptName_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string dept_name = 9;</code>
			 *
			 * <pre>
			 * 部门名称
			 * </pre>
			 */
			public com.google.protobuf.ByteString getDeptNameBytes() {
				java.lang.Object ref = deptName_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					deptName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string dept_name = 9;</code>
			 *
			 * <pre>
			 * 部门名称
			 * </pre>
			 */
			public Builder setDeptName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000100;
				deptName_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string dept_name = 9;</code>
			 *
			 * <pre>
			 * 部门名称
			 * </pre>
			 */
			public Builder clearDeptName() {
				bitField0_ = (bitField0_ & ~0x00000100);
				deptName_ = getDefaultInstance().getDeptName();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string dept_name = 9;</code>
			 *
			 * <pre>
			 * 部门名称
			 * </pre>
			 */
			public Builder setDeptNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000100;
				deptName_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object deptCode_ = "";

			/**
			 * <code>optional string dept_code = 10;</code>
			 *
			 * <pre>
			 * 部门编码
			 * </pre>
			 */
			public boolean hasDeptCode() {
				return ((bitField0_ & 0x00000200) == 0x00000200);
			}

			/**
			 * <code>optional string dept_code = 10;</code>
			 *
			 * <pre>
			 * 部门编码
			 * </pre>
			 */
			public java.lang.String getDeptCode() {
				java.lang.Object ref = deptCode_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						deptCode_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string dept_code = 10;</code>
			 *
			 * <pre>
			 * 部门编码
			 * </pre>
			 */
			public com.google.protobuf.ByteString getDeptCodeBytes() {
				java.lang.Object ref = deptCode_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					deptCode_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string dept_code = 10;</code>
			 *
			 * <pre>
			 * 部门编码
			 * </pre>
			 */
			public Builder setDeptCode(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000200;
				deptCode_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string dept_code = 10;</code>
			 *
			 * <pre>
			 * 部门编码
			 * </pre>
			 */
			public Builder clearDeptCode() {
				bitField0_ = (bitField0_ & ~0x00000200);
				deptCode_ = getDefaultInstance().getDeptCode();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string dept_code = 10;</code>
			 *
			 * <pre>
			 * 部门编码
			 * </pre>
			 */
			public Builder setDeptCodeBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000200;
				deptCode_ = value;
				onChanged();
				return this;
			}

			private int deviceL1Id_;

			/**
			 * <code>optional int32 deviceL1_id = 11;</code>
			 *
			 * <pre>
			 * 一级设备Id
			 * </pre>
			 */
			public boolean hasDeviceL1Id() {
				return ((bitField0_ & 0x00000400) == 0x00000400);
			}

			/**
			 * <code>optional int32 deviceL1_id = 11;</code>
			 *
			 * <pre>
			 * 一级设备Id
			 * </pre>
			 */
			public int getDeviceL1Id() {
				return deviceL1Id_;
			}

			/**
			 * <code>optional int32 deviceL1_id = 11;</code>
			 *
			 * <pre>
			 * 一级设备Id
			 * </pre>
			 */
			public Builder setDeviceL1Id(int value) {
				bitField0_ |= 0x00000400;
				deviceL1Id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 deviceL1_id = 11;</code>
			 *
			 * <pre>
			 * 一级设备Id
			 * </pre>
			 */
			public Builder clearDeviceL1Id() {
				bitField0_ = (bitField0_ & ~0x00000400);
				deviceL1Id_ = 0;
				onChanged();
				return this;
			}

			private int deviceL1Type_;

			/**
			 * <code>optional int32 deviceL1_type = 12;</code>
			 *
			 * <pre>
			 * 一级设备类型
			 * </pre>
			 */
			public boolean hasDeviceL1Type() {
				return ((bitField0_ & 0x00000800) == 0x00000800);
			}

			/**
			 * <code>optional int32 deviceL1_type = 12;</code>
			 *
			 * <pre>
			 * 一级设备类型
			 * </pre>
			 */
			public int getDeviceL1Type() {
				return deviceL1Type_;
			}

			/**
			 * <code>optional int32 deviceL1_type = 12;</code>
			 *
			 * <pre>
			 * 一级设备类型
			 * </pre>
			 */
			public Builder setDeviceL1Type(int value) {
				bitField0_ |= 0x00000800;
				deviceL1Type_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 deviceL1_type = 12;</code>
			 *
			 * <pre>
			 * 一级设备类型
			 * </pre>
			 */
			public Builder clearDeviceL1Type() {
				bitField0_ = (bitField0_ & ~0x00000800);
				deviceL1Type_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object deviceL1Name_ = "";

			/**
			 * <code>optional string deviceL1_name = 13;</code>
			 *
			 * <pre>
			 * 一级设备名称
			 * </pre>
			 */
			public boolean hasDeviceL1Name() {
				return ((bitField0_ & 0x00001000) == 0x00001000);
			}

			/**
			 * <code>optional string deviceL1_name = 13;</code>
			 *
			 * <pre>
			 * 一级设备名称
			 * </pre>
			 */
			public java.lang.String getDeviceL1Name() {
				java.lang.Object ref = deviceL1Name_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						deviceL1Name_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string deviceL1_name = 13;</code>
			 *
			 * <pre>
			 * 一级设备名称
			 * </pre>
			 */
			public com.google.protobuf.ByteString getDeviceL1NameBytes() {
				java.lang.Object ref = deviceL1Name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					deviceL1Name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string deviceL1_name = 13;</code>
			 *
			 * <pre>
			 * 一级设备名称
			 * </pre>
			 */
			public Builder setDeviceL1Name(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00001000;
				deviceL1Name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string deviceL1_name = 13;</code>
			 *
			 * <pre>
			 * 一级设备名称
			 * </pre>
			 */
			public Builder clearDeviceL1Name() {
				bitField0_ = (bitField0_ & ~0x00001000);
				deviceL1Name_ = getDefaultInstance().getDeviceL1Name();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string deviceL1_name = 13;</code>
			 *
			 * <pre>
			 * 一级设备名称
			 * </pre>
			 */
			public Builder setDeviceL1NameBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00001000;
				deviceL1Name_ = value;
				onChanged();
				return this;
			}

			private int deviceL2Id_;

			/**
			 * <code>optional int32 deviceL2_id = 14;</code>
			 *
			 * <pre>
			 * 二级设备Id
			 * </pre>
			 */
			public boolean hasDeviceL2Id() {
				return ((bitField0_ & 0x00002000) == 0x00002000);
			}

			/**
			 * <code>optional int32 deviceL2_id = 14;</code>
			 *
			 * <pre>
			 * 二级设备Id
			 * </pre>
			 */
			public int getDeviceL2Id() {
				return deviceL2Id_;
			}

			/**
			 * <code>optional int32 deviceL2_id = 14;</code>
			 *
			 * <pre>
			 * 二级设备Id
			 * </pre>
			 */
			public Builder setDeviceL2Id(int value) {
				bitField0_ |= 0x00002000;
				deviceL2Id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 deviceL2_id = 14;</code>
			 *
			 * <pre>
			 * 二级设备Id
			 * </pre>
			 */
			public Builder clearDeviceL2Id() {
				bitField0_ = (bitField0_ & ~0x00002000);
				deviceL2Id_ = 0;
				onChanged();
				return this;
			}

			private int deviceL2Type_;

			/**
			 * <code>optional int32 deviceL2_type = 15;</code>
			 *
			 * <pre>
			 * 二级设备类型
			 * </pre>
			 */
			public boolean hasDeviceL2Type() {
				return ((bitField0_ & 0x00004000) == 0x00004000);
			}

			/**
			 * <code>optional int32 deviceL2_type = 15;</code>
			 *
			 * <pre>
			 * 二级设备类型
			 * </pre>
			 */
			public int getDeviceL2Type() {
				return deviceL2Type_;
			}

			/**
			 * <code>optional int32 deviceL2_type = 15;</code>
			 *
			 * <pre>
			 * 二级设备类型
			 * </pre>
			 */
			public Builder setDeviceL2Type(int value) {
				bitField0_ |= 0x00004000;
				deviceL2Type_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 deviceL2_type = 15;</code>
			 *
			 * <pre>
			 * 二级设备类型
			 * </pre>
			 */
			public Builder clearDeviceL2Type() {
				bitField0_ = (bitField0_ & ~0x00004000);
				deviceL2Type_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object deviceL2Name_ = "";

			/**
			 * <code>optional string deviceL2_name = 16;</code>
			 *
			 * <pre>
			 * 二级设备名称
			 * </pre>
			 */
			public boolean hasDeviceL2Name() {
				return ((bitField0_ & 0x00008000) == 0x00008000);
			}

			/**
			 * <code>optional string deviceL2_name = 16;</code>
			 *
			 * <pre>
			 * 二级设备名称
			 * </pre>
			 */
			public java.lang.String getDeviceL2Name() {
				java.lang.Object ref = deviceL2Name_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						deviceL2Name_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string deviceL2_name = 16;</code>
			 *
			 * <pre>
			 * 二级设备名称
			 * </pre>
			 */
			public com.google.protobuf.ByteString getDeviceL2NameBytes() {
				java.lang.Object ref = deviceL2Name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					deviceL2Name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string deviceL2_name = 16;</code>
			 *
			 * <pre>
			 * 二级设备名称
			 * </pre>
			 */
			public Builder setDeviceL2Name(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00008000;
				deviceL2Name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string deviceL2_name = 16;</code>
			 *
			 * <pre>
			 * 二级设备名称
			 * </pre>
			 */
			public Builder clearDeviceL2Name() {
				bitField0_ = (bitField0_ & ~0x00008000);
				deviceL2Name_ = getDefaultInstance().getDeviceL2Name();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string deviceL2_name = 16;</code>
			 *
			 * <pre>
			 * 二级设备名称
			 * </pre>
			 */
			public Builder setDeviceL2NameBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00008000;
				deviceL2Name_ = value;
				onChanged();
				return this;
			}

			private int deviceL3Id_;

			/**
			 * <code>optional int32 deviceL3_id = 17;</code>
			 *
			 * <pre>
			 * 三级设备Id
			 * </pre>
			 */
			public boolean hasDeviceL3Id() {
				return ((bitField0_ & 0x00010000) == 0x00010000);
			}

			/**
			 * <code>optional int32 deviceL3_id = 17;</code>
			 *
			 * <pre>
			 * 三级设备Id
			 * </pre>
			 */
			public int getDeviceL3Id() {
				return deviceL3Id_;
			}

			/**
			 * <code>optional int32 deviceL3_id = 17;</code>
			 *
			 * <pre>
			 * 三级设备Id
			 * </pre>
			 */
			public Builder setDeviceL3Id(int value) {
				bitField0_ |= 0x00010000;
				deviceL3Id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 deviceL3_id = 17;</code>
			 *
			 * <pre>
			 * 三级设备Id
			 * </pre>
			 */
			public Builder clearDeviceL3Id() {
				bitField0_ = (bitField0_ & ~0x00010000);
				deviceL3Id_ = 0;
				onChanged();
				return this;
			}

			private int deviceL3Type_;

			/**
			 * <code>optional int32 deviceL3_type = 18;</code>
			 *
			 * <pre>
			 * 三级设备类型
			 * </pre>
			 */
			public boolean hasDeviceL3Type() {
				return ((bitField0_ & 0x00020000) == 0x00020000);
			}

			/**
			 * <code>optional int32 deviceL3_type = 18;</code>
			 *
			 * <pre>
			 * 三级设备类型
			 * </pre>
			 */
			public int getDeviceL3Type() {
				return deviceL3Type_;
			}

			/**
			 * <code>optional int32 deviceL3_type = 18;</code>
			 *
			 * <pre>
			 * 三级设备类型
			 * </pre>
			 */
			public Builder setDeviceL3Type(int value) {
				bitField0_ |= 0x00020000;
				deviceL3Type_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 deviceL3_type = 18;</code>
			 *
			 * <pre>
			 * 三级设备类型
			 * </pre>
			 */
			public Builder clearDeviceL3Type() {
				bitField0_ = (bitField0_ & ~0x00020000);
				deviceL3Type_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object deviceL3Name_ = "";

			/**
			 * <code>optional string deviceL3_name = 19;</code>
			 *
			 * <pre>
			 * 三级设备名称
			 * </pre>
			 */
			public boolean hasDeviceL3Name() {
				return ((bitField0_ & 0x00040000) == 0x00040000);
			}

			/**
			 * <code>optional string deviceL3_name = 19;</code>
			 *
			 * <pre>
			 * 三级设备名称
			 * </pre>
			 */
			public java.lang.String getDeviceL3Name() {
				java.lang.Object ref = deviceL3Name_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						deviceL3Name_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string deviceL3_name = 19;</code>
			 *
			 * <pre>
			 * 三级设备名称
			 * </pre>
			 */
			public com.google.protobuf.ByteString getDeviceL3NameBytes() {
				java.lang.Object ref = deviceL3Name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					deviceL3Name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string deviceL3_name = 19;</code>
			 *
			 * <pre>
			 * 三级设备名称
			 * </pre>
			 */
			public Builder setDeviceL3Name(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00040000;
				deviceL3Name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string deviceL3_name = 19;</code>
			 *
			 * <pre>
			 * 三级设备名称
			 * </pre>
			 */
			public Builder clearDeviceL3Name() {
				bitField0_ = (bitField0_ & ~0x00040000);
				deviceL3Name_ = getDefaultInstance().getDeviceL3Name();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string deviceL3_name = 19;</code>
			 *
			 * <pre>
			 * 三级设备名称
			 * </pre>
			 */
			public Builder setDeviceL3NameBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00040000;
				deviceL3Name_ = value;
				onChanged();
				return this;
			}

			private int inOut_;

			/**
			 * <code>optional int32 in_out = 20;</code>
			 *
			 * <pre>
			 * 进出方向
			 * </pre>
			 */
			public boolean hasInOut() {
				return ((bitField0_ & 0x00080000) == 0x00080000);
			}

			/**
			 * <code>optional int32 in_out = 20;</code>
			 *
			 * <pre>
			 * 进出方向
			 * </pre>
			 */
			public int getInOut() {
				return inOut_;
			}

			/**
			 * <code>optional int32 in_out = 20;</code>
			 *
			 * <pre>
			 * 进出方向
			 * </pre>
			 */
			public Builder setInOut(int value) {
				bitField0_ |= 0x00080000;
				inOut_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 in_out = 20;</code>
			 *
			 * <pre>
			 * 进出方向
			 * </pre>
			 */
			public Builder clearInOut() {
				bitField0_ = (bitField0_ & ~0x00080000);
				inOut_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object extTxt_ = "";

			/**
			 * <code>optional string ext_txt = 21;</code>
			 *
			 * <pre>
			 * DAG上报的扩展信息内容，xml
			 * </pre>
			 */
			public boolean hasExtTxt() {
				return ((bitField0_ & 0x00100000) == 0x00100000);
			}

			/**
			 * <code>optional string ext_txt = 21;</code>
			 *
			 * <pre>
			 * DAG上报的扩展信息内容，xml
			 * </pre>
			 */
			public java.lang.String getExtTxt() {
				java.lang.Object ref = extTxt_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						extTxt_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string ext_txt = 21;</code>
			 *
			 * <pre>
			 * DAG上报的扩展信息内容，xml
			 * </pre>
			 */
			public com.google.protobuf.ByteString getExtTxtBytes() {
				java.lang.Object ref = extTxt_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					extTxt_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string ext_txt = 21;</code>
			 *
			 * <pre>
			 * DAG上报的扩展信息内容，xml
			 * </pre>
			 */
			public Builder setExtTxt(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00100000;
				extTxt_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string ext_txt = 21;</code>
			 *
			 * <pre>
			 * DAG上报的扩展信息内容，xml
			 * </pre>
			 */
			public Builder clearExtTxt() {
				bitField0_ = (bitField0_ & ~0x00100000);
				extTxt_ = getDefaultInstance().getExtTxt();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string ext_txt = 21;</code>
			 *
			 * <pre>
			 * DAG上报的扩展信息内容，xml
			 * </pre>
			 */
			public Builder setExtTxtBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00100000;
				extTxt_ = value;
				onChanged();
				return this;
			}

			private int doorId_;

			/**
			 * <code>optional int32 door_id = 33;</code>
			 *
			 * <pre>
			 * 门Id
			 * </pre>
			 */
			public boolean hasDoorId() {
				return ((bitField0_ & 0x00200000) == 0x00200000);
			}

			/**
			 * <code>optional int32 door_id = 33;</code>
			 *
			 * <pre>
			 * 门Id
			 * </pre>
			 */
			public int getDoorId() {
				return doorId_;
			}

			/**
			 * <code>optional int32 door_id = 33;</code>
			 *
			 * <pre>
			 * 门Id
			 * </pre>
			 */
			public Builder setDoorId(int value) {
				bitField0_ |= 0x00200000;
				doorId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 door_id = 33;</code>
			 *
			 * <pre>
			 * 门Id
			 * </pre>
			 */
			public Builder clearDoorId() {
				bitField0_ = (bitField0_ & ~0x00200000);
				doorId_ = 0;
				onChanged();
				return this;
			}

			private int cardStatus_;

			/**
			 * <code>optional int32 card_status = 34;</code>
			 *
			 * <pre>
			 * 卡状态
			 * </pre>
			 */
			public boolean hasCardStatus() {
				return ((bitField0_ & 0x00400000) == 0x00400000);
			}

			/**
			 * <code>optional int32 card_status = 34;</code>
			 *
			 * <pre>
			 * 卡状态
			 * </pre>
			 */
			public int getCardStatus() {
				return cardStatus_;
			}

			/**
			 * <code>optional int32 card_status = 34;</code>
			 *
			 * <pre>
			 * 卡状态
			 * </pre>
			 */
			public Builder setCardStatus(int value) {
				bitField0_ |= 0x00400000;
				cardStatus_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 card_status = 34;</code>
			 *
			 * <pre>
			 * 卡状态
			 * </pre>
			 */
			public Builder clearCardStatus() {
				bitField0_ = (bitField0_ & ~0x00400000);
				cardStatus_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object picUrl_ = "";

			/**
			 * <code>optional string pic_url = 35;</code>
			 *
			 * <pre>
			 * 图片url
			 * </pre>
			 */
			public boolean hasPicUrl() {
				return ((bitField0_ & 0x00800000) == 0x00800000);
			}

			/**
			 * <code>optional string pic_url = 35;</code>
			 *
			 * <pre>
			 * 图片url
			 * </pre>
			 */
			public java.lang.String getPicUrl() {
				java.lang.Object ref = picUrl_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						picUrl_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string pic_url = 35;</code>
			 *
			 * <pre>
			 * 图片url
			 * </pre>
			 */
			public com.google.protobuf.ByteString getPicUrlBytes() {
				java.lang.Object ref = picUrl_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					picUrl_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string pic_url = 35;</code>
			 *
			 * <pre>
			 * 图片url
			 * </pre>
			 */
			public Builder setPicUrl(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00800000;
				picUrl_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string pic_url = 35;</code>
			 *
			 * <pre>
			 * 图片url
			 * </pre>
			 */
			public Builder clearPicUrl() {
				bitField0_ = (bitField0_ & ~0x00800000);
				picUrl_ = getDefaultInstance().getPicUrl();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string pic_url = 35;</code>
			 *
			 * <pre>
			 * 图片url
			 * </pre>
			 */
			public Builder setPicUrlBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00800000;
				picUrl_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:net.zdsoft.officework.mqreceive.AccessEventLog)
		}

		static {
			defaultInstance = new AccessEventLog(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:net.zdsoft.officework.mqreceive.AccessEventLog)
		
		  public String toJsonString(){
			  JSONObject json = new JSONObject();
			  for (final Map.Entry<FieldDescriptor, Object> field :
			         this.getAllFields().entrySet()) {
				  json.put(field.getKey().getName(), field.getValue());
			    }
			  return json.toJSONString();
		  }
	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {
				"\n\017acs_event.proto\022\037net.zdsoft.officework"
						+ ".mqreceive\032\ncomm.proto\"\365\003\n\016AccessEventLo"
						+ "g\022\022\n\nevent_code\030\001 \001(\005\022\021\n\tdevice_id\030\002 \001(\005"
						+ "\022\023\n\013device_type\030\003 \001(\005\022\023\n\013device_name\030\004 \001"
						+ "(\t\022\022\n\nevent_card\030\005 \001(\t\022\021\n\tperson_id\030\006 \001("
						+ "\005\022\023\n\013person_name\030\007 \001(\t\022\017\n\007dept_id\030\010 \001(\005\022"
						+ "\021\n\tdept_name\030\t \001(\t\022\021\n\tdept_code\030\n \001(\t\022\023\n"
						+ "\013deviceL1_id\030\013 \001(\005\022\025\n\rdeviceL1_type\030\014 \001("
						+ "\005\022\025\n\rdeviceL1_name\030\r \001(\t\022\023\n\013deviceL2_id\030"
						+ "\016 \001(\005\022\025\n\rdeviceL2_type\030\017 \001(\005\022\025\n\rdeviceL2",
				"_name\030\020 \001(\t\022\023\n\013deviceL3_id\030\021 \001(\005\022\025\n\rdevi"
						+ "ceL3_type\030\022 \001(\005\022\025\n\rdeviceL3_name\030\023 \001(\t\022\016"
						+ "\n\006in_out\030\024 \001(\005\022\017\n\007ext_txt\030\025 \001(\t\022\017\n\007door_"
						+ "id\030! \001(\005\022\023\n\013card_status\030\" \001(\005\022\017\n\007pic_url"
						+ "\030# \001(\t" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] { net.zdsoft.officework.mqreceive.Comm
								.getDescriptor(), }, assigner);
		internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_descriptor = getDescriptor()
				.getMessageTypes().get(0);
		internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_net_zdsoft_officework_mqreceive_AccessEventLog_descriptor,
				new java.lang.String[] { "EventCode", "DeviceId", "DeviceType",
						"DeviceName", "EventCard", "PersonId", "PersonName",
						"DeptId", "DeptName", "DeptCode", "DeviceL1Id",
						"DeviceL1Type", "DeviceL1Name", "DeviceL2Id",
						"DeviceL2Type", "DeviceL2Name", "DeviceL3Id",
						"DeviceL3Type", "DeviceL3Name", "InOut", "ExtTxt",
						"DoorId", "CardStatus", "PicUrl", });
		net.zdsoft.officework.mqreceive.Comm.getDescriptor();

	}

	// @@protoc_insertion_point(outer_class_scope)
}
