// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comm.proto

package net.zdsoft.officework.mqreceive;

import java.util.Map;

import com.alibaba.fastjson.JSONObject;
import com.google.protobuf.Descriptors.FieldDescriptor;

public final class Comm {
  private Comm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code net.zdsoft.officework.mqreceive.EventState}
   *
   * <pre>
   *&#64;事件状态定义
   * </pre>
   */
  public enum EventState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EVENT_STATE_INSTANT = 0;</code>
     *
     * <pre>
     *瞬时事件，保存
     * </pre>
     */
    EVENT_STATE_INSTANT(0, 0),
    /**
     * <code>EVENT_STATE_START = 1;</code>
     *
     * <pre>
     *事件开始，保存
     * </pre>
     */
    EVENT_STATE_START(1, 1),
    /**
     * <code>EVENT_STATE_STOP = 2;</code>
     *
     * <pre>
     *事件结束，更新结束时间
     * </pre>
     */
    EVENT_STATE_STOP(2, 2),
    /**
     * <code>EVENT_STATE_PULSE = 3;</code>
     *
     * <pre>
     *事件脉冲，客户端和服务器使用，CMS不用
     * </pre>
     */
    EVENT_STATE_PULSE(3, 3),
    /**
     * <code>EVENT_STATE_UPDATE = 4;</code>
     *
     * <pre>
     *事件更新，联动结果更新
     * </pre>
     */
    EVENT_STATE_UPDATE(4, 4),
    ;

    /**
     * <code>EVENT_STATE_INSTANT = 0;</code>
     *
     * <pre>
     *瞬时事件，保存
     * </pre>
     */
    public static final int EVENT_STATE_INSTANT_VALUE = 0;
    /**
     * <code>EVENT_STATE_START = 1;</code>
     *
     * <pre>
     *事件开始，保存
     * </pre>
     */
    public static final int EVENT_STATE_START_VALUE = 1;
    /**
     * <code>EVENT_STATE_STOP = 2;</code>
     *
     * <pre>
     *事件结束，更新结束时间
     * </pre>
     */
    public static final int EVENT_STATE_STOP_VALUE = 2;
    /**
     * <code>EVENT_STATE_PULSE = 3;</code>
     *
     * <pre>
     *事件脉冲，客户端和服务器使用，CMS不用
     * </pre>
     */
    public static final int EVENT_STATE_PULSE_VALUE = 3;
    /**
     * <code>EVENT_STATE_UPDATE = 4;</code>
     *
     * <pre>
     *事件更新，联动结果更新
     * </pre>
     */
    public static final int EVENT_STATE_UPDATE_VALUE = 4;


    public final int getNumber() { return value; }

    public static EventState valueOf(int value) {
      switch (value) {
        case 0: return EVENT_STATE_INSTANT;
        case 1: return EVENT_STATE_START;
        case 2: return EVENT_STATE_STOP;
        case 3: return EVENT_STATE_PULSE;
        case 4: return EVENT_STATE_UPDATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EventState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventState>() {
            public EventState findValueByNumber(int number) {
              return EventState.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.zdsoft.officework.mqreceive.Comm.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventState[] VALUES = values();

    public static EventState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EventState(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:net.zdsoft.officework.mqreceive.EventState)
  }

  /**
   * Protobuf enum {@code net.zdsoft.officework.mqreceive.MsgCmdType}
   *
   * <pre>
   *&#64;与事件分发服务通信的命令码定义
   * </pre>
   */
  public enum MsgCmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_CMD_TYPE_MASK = 65280;</code>
     *
     * <pre>
     *client msg 0x000001xxx
     * </pre>
     */
    MSG_CMD_TYPE_MASK(0, 65280),
    /**
     * <code>MSG_CMD_MANUAL_EVENT = 257;</code>
     *
     * <pre>
     *手动事件命令码
     * </pre>
     */
    MSG_CMD_MANUAL_EVENT(1, 257),
    /**
     * <code>MSG_CMD_CONFIRM_EVENT = 258;</code>
     *
     * <pre>
     *报警确认命令码
     * </pre>
     */
    MSG_CMD_CONFIRM_EVENT(2, 258),
    /**
     * <code>MSG_CMD_REPORT_EVENT = 513;</code>
     *
     * <pre>
     *xx_2_eds msg 0x000002xxx
     * </pre>
     */
    MSG_CMD_REPORT_EVENT(3, 513),
    /**
     * <code>MSG_CMD_SUBRECV_EVENT = 514;</code>
     *
     * <pre>
     *订阅事件命令码
     * </pre>
     */
    MSG_CMD_SUBRECV_EVENT(4, 514),
    /**
     * <code>MSG_CMD_EVENT_NOTIFY_REQ = 769;</code>
     *
     * <pre>
     *eds_2_eds msg 0x000003xxx
     * </pre>
     */
    MSG_CMD_EVENT_NOTIFY_REQ(5, 769),
    /**
     * <code>MSG_CMD_EVENT_NOTIFY_RSP = 770;</code>
     *
     * <pre>
     *事件分发服务内部事件通知响应
     * </pre>
     */
    MSG_CMD_EVENT_NOTIFY_RSP(6, 770),
    ;

    /**
     * <code>MSG_CMD_TYPE_MASK = 65280;</code>
     *
     * <pre>
     *client msg 0x000001xxx
     * </pre>
     */
    public static final int MSG_CMD_TYPE_MASK_VALUE = 65280;
    /**
     * <code>MSG_CMD_MANUAL_EVENT = 257;</code>
     *
     * <pre>
     *手动事件命令码
     * </pre>
     */
    public static final int MSG_CMD_MANUAL_EVENT_VALUE = 257;
    /**
     * <code>MSG_CMD_CONFIRM_EVENT = 258;</code>
     *
     * <pre>
     *报警确认命令码
     * </pre>
     */
    public static final int MSG_CMD_CONFIRM_EVENT_VALUE = 258;
    /**
     * <code>MSG_CMD_REPORT_EVENT = 513;</code>
     *
     * <pre>
     *xx_2_eds msg 0x000002xxx
     * </pre>
     */
    public static final int MSG_CMD_REPORT_EVENT_VALUE = 513;
    /**
     * <code>MSG_CMD_SUBRECV_EVENT = 514;</code>
     *
     * <pre>
     *订阅事件命令码
     * </pre>
     */
    public static final int MSG_CMD_SUBRECV_EVENT_VALUE = 514;
    /**
     * <code>MSG_CMD_EVENT_NOTIFY_REQ = 769;</code>
     *
     * <pre>
     *eds_2_eds msg 0x000003xxx
     * </pre>
     */
    public static final int MSG_CMD_EVENT_NOTIFY_REQ_VALUE = 769;
    /**
     * <code>MSG_CMD_EVENT_NOTIFY_RSP = 770;</code>
     *
     * <pre>
     *事件分发服务内部事件通知响应
     * </pre>
     */
    public static final int MSG_CMD_EVENT_NOTIFY_RSP_VALUE = 770;


    public final int getNumber() { return value; }

    public static MsgCmdType valueOf(int value) {
      switch (value) {
        case 65280: return MSG_CMD_TYPE_MASK;
        case 257: return MSG_CMD_MANUAL_EVENT;
        case 258: return MSG_CMD_CONFIRM_EVENT;
        case 513: return MSG_CMD_REPORT_EVENT;
        case 514: return MSG_CMD_SUBRECV_EVENT;
        case 769: return MSG_CMD_EVENT_NOTIFY_REQ;
        case 770: return MSG_CMD_EVENT_NOTIFY_RSP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgCmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgCmdType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgCmdType>() {
            public MsgCmdType findValueByNumber(int number) {
              return MsgCmdType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.zdsoft.officework.mqreceive.Comm.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgCmdType[] VALUES = values();

    public static MsgCmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgCmdType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:net.zdsoft.officework.mqreceive.MsgCmdType)
  }

  public interface TriggerResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.zdsoft.officework.mqreceive.TriggerResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 trigger_type = 1;</code>
     *
     * <pre>
     *联动类型: 参见联动类型定义
     * </pre>
     */
    boolean hasTriggerType();
    /**
     * <code>required int32 trigger_type = 1;</code>
     *
     * <pre>
     *联动类型: 参见联动类型定义
     * </pre>
     */
    int getTriggerType();

    /**
     * <code>repeated int32 trigger_ret = 2;</code>
     *
     * <pre>
     *联动结果
     * </pre>
     */
    java.util.List<java.lang.Integer> getTriggerRetList();
    /**
     * <code>repeated int32 trigger_ret = 2;</code>
     *
     * <pre>
     *联动结果
     * </pre>
     */
    int getTriggerRetCount();
    /**
     * <code>repeated int32 trigger_ret = 2;</code>
     *
     * <pre>
     *联动结果
     * </pre>
     */
    int getTriggerRet(int index);

    /**
     * <code>required string trigger_time = 3;</code>
     *
     * <pre>
     *联动执行时间(确认时为确认时间)
     * </pre>
     */
    boolean hasTriggerTime();
    /**
     * <code>required string trigger_time = 3;</code>
     *
     * <pre>
     *联动执行时间(确认时为确认时间)
     * </pre>
     */
    java.lang.String getTriggerTime();
    /**
     * <code>required string trigger_time = 3;</code>
     *
     * <pre>
     *联动执行时间(确认时为确认时间)
     * </pre>
     */
    com.google.protobuf.ByteString
        getTriggerTimeBytes();

    /**
     * <code>optional string trigger_info = 33;</code>
     *
     * <pre>
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     * </pre>
     */
    boolean hasTriggerInfo();
    /**
     * <code>optional string trigger_info = 33;</code>
     *
     * <pre>
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     * </pre>
     */
    java.lang.String getTriggerInfo();
    /**
     * <code>optional string trigger_info = 33;</code>
     *
     * <pre>
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     * </pre>
     */
    com.google.protobuf.ByteString
        getTriggerInfoBytes();

    /**
     * <code>optional string err_msg = 34;</code>
     *
     * <pre>
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     * </pre>
     */
    boolean hasErrMsg();
    /**
     * <code>optional string err_msg = 34;</code>
     *
     * <pre>
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     * </pre>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string err_msg = 34;</code>
     *
     * <pre>
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code net.zdsoft.officework.mqreceive.TriggerResult}
   *
   * <pre>
   *&#64;事件处理结果消息结构体
   * </pre>
   */
  public static final class TriggerResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:net.zdsoft.officework.mqreceive.TriggerResult)
      TriggerResultOrBuilder {
    // Use TriggerResult.newBuilder() to construct.
    private TriggerResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TriggerResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TriggerResult defaultInstance;
    public static TriggerResult getDefaultInstance() {
      return defaultInstance;
    }

    public TriggerResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TriggerResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              triggerType_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                triggerRet_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              triggerRet_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                triggerRet_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                triggerRet_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              triggerTime_ = bs;
              break;
            }
            case 266: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              triggerInfo_ = bs;
              break;
            }
            case 274: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              errMsg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          triggerRet_ = java.util.Collections.unmodifiableList(triggerRet_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_TriggerResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_TriggerResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.zdsoft.officework.mqreceive.Comm.TriggerResult.class, net.zdsoft.officework.mqreceive.Comm.TriggerResult.Builder.class);
    }

    public static com.google.protobuf.Parser<TriggerResult> PARSER =
        new com.google.protobuf.AbstractParser<TriggerResult>() {
      public TriggerResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TriggerResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TriggerResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRIGGER_TYPE_FIELD_NUMBER = 1;
    private int triggerType_;
    /**
     * <code>required int32 trigger_type = 1;</code>
     *
     * <pre>
     *联动类型: 参见联动类型定义
     * </pre>
     */
    public boolean hasTriggerType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 trigger_type = 1;</code>
     *
     * <pre>
     *联动类型: 参见联动类型定义
     * </pre>
     */
    public int getTriggerType() {
      return triggerType_;
    }

    public static final int TRIGGER_RET_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> triggerRet_;
    /**
     * <code>repeated int32 trigger_ret = 2;</code>
     *
     * <pre>
     *联动结果
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getTriggerRetList() {
      return triggerRet_;
    }
    /**
     * <code>repeated int32 trigger_ret = 2;</code>
     *
     * <pre>
     *联动结果
     * </pre>
     */
    public int getTriggerRetCount() {
      return triggerRet_.size();
    }
    /**
     * <code>repeated int32 trigger_ret = 2;</code>
     *
     * <pre>
     *联动结果
     * </pre>
     */
    public int getTriggerRet(int index) {
      return triggerRet_.get(index);
    }

    public static final int TRIGGER_TIME_FIELD_NUMBER = 3;
    private java.lang.Object triggerTime_;
    /**
     * <code>required string trigger_time = 3;</code>
     *
     * <pre>
     *联动执行时间(确认时为确认时间)
     * </pre>
     */
    public boolean hasTriggerTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string trigger_time = 3;</code>
     *
     * <pre>
     *联动执行时间(确认时为确认时间)
     * </pre>
     */
    public java.lang.String getTriggerTime() {
      java.lang.Object ref = triggerTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          triggerTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string trigger_time = 3;</code>
     *
     * <pre>
     *联动执行时间(确认时为确认时间)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTriggerTimeBytes() {
      java.lang.Object ref = triggerTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        triggerTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIGGER_INFO_FIELD_NUMBER = 33;
    private java.lang.Object triggerInfo_;
    /**
     * <code>optional string trigger_info = 33;</code>
     *
     * <pre>
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     * </pre>
     */
    public boolean hasTriggerInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string trigger_info = 33;</code>
     *
     * <pre>
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     * </pre>
     */
    public java.lang.String getTriggerInfo() {
      java.lang.Object ref = triggerInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          triggerInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trigger_info = 33;</code>
     *
     * <pre>
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTriggerInfoBytes() {
      java.lang.Object ref = triggerInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        triggerInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERR_MSG_FIELD_NUMBER = 34;
    private java.lang.Object errMsg_;
    /**
     * <code>optional string err_msg = 34;</code>
     *
     * <pre>
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     * </pre>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string err_msg = 34;</code>
     *
     * <pre>
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     * </pre>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string err_msg = 34;</code>
     *
     * <pre>
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      triggerType_ = 0;
      triggerRet_ = java.util.Collections.emptyList();
      triggerTime_ = "";
      triggerInfo_ = "";
      errMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTriggerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTriggerTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, triggerType_);
      }
      for (int i = 0; i < triggerRet_.size(); i++) {
        output.writeInt32(2, triggerRet_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getTriggerTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(33, getTriggerInfoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(34, getErrMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, triggerType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < triggerRet_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(triggerRet_.get(i));
        }
        size += dataSize;
        size += 1 * getTriggerRetList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTriggerTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(33, getTriggerInfoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(34, getErrMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.zdsoft.officework.mqreceive.Comm.TriggerResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.zdsoft.officework.mqreceive.Comm.TriggerResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.zdsoft.officework.mqreceive.TriggerResult}
     *
     * <pre>
     *&#64;事件处理结果消息结构体
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.zdsoft.officework.mqreceive.TriggerResult)
        net.zdsoft.officework.mqreceive.Comm.TriggerResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_TriggerResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_TriggerResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.zdsoft.officework.mqreceive.Comm.TriggerResult.class, net.zdsoft.officework.mqreceive.Comm.TriggerResult.Builder.class);
      }

      // Construct using net.zdsoft.officework.mqreceive.Comm.TriggerResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        triggerType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        triggerRet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        triggerTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        triggerInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_TriggerResult_descriptor;
      }

      public net.zdsoft.officework.mqreceive.Comm.TriggerResult getDefaultInstanceForType() {
        return net.zdsoft.officework.mqreceive.Comm.TriggerResult.getDefaultInstance();
      }

      public net.zdsoft.officework.mqreceive.Comm.TriggerResult build() {
        net.zdsoft.officework.mqreceive.Comm.TriggerResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.zdsoft.officework.mqreceive.Comm.TriggerResult buildPartial() {
        net.zdsoft.officework.mqreceive.Comm.TriggerResult result = new net.zdsoft.officework.mqreceive.Comm.TriggerResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.triggerType_ = triggerType_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          triggerRet_ = java.util.Collections.unmodifiableList(triggerRet_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.triggerRet_ = triggerRet_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.triggerTime_ = triggerTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.triggerInfo_ = triggerInfo_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errMsg_ = errMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.zdsoft.officework.mqreceive.Comm.TriggerResult) {
          return mergeFrom((net.zdsoft.officework.mqreceive.Comm.TriggerResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.zdsoft.officework.mqreceive.Comm.TriggerResult other) {
        if (other == net.zdsoft.officework.mqreceive.Comm.TriggerResult.getDefaultInstance()) return this;
        if (other.hasTriggerType()) {
          setTriggerType(other.getTriggerType());
        }
        if (!other.triggerRet_.isEmpty()) {
          if (triggerRet_.isEmpty()) {
            triggerRet_ = other.triggerRet_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTriggerRetIsMutable();
            triggerRet_.addAll(other.triggerRet_);
          }
          onChanged();
        }
        if (other.hasTriggerTime()) {
          bitField0_ |= 0x00000004;
          triggerTime_ = other.triggerTime_;
          onChanged();
        }
        if (other.hasTriggerInfo()) {
          bitField0_ |= 0x00000008;
          triggerInfo_ = other.triggerInfo_;
          onChanged();
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000010;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTriggerType()) {
          
          return false;
        }
        if (!hasTriggerTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.zdsoft.officework.mqreceive.Comm.TriggerResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.zdsoft.officework.mqreceive.Comm.TriggerResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int triggerType_ ;
      /**
       * <code>required int32 trigger_type = 1;</code>
       *
       * <pre>
       *联动类型: 参见联动类型定义
       * </pre>
       */
      public boolean hasTriggerType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 trigger_type = 1;</code>
       *
       * <pre>
       *联动类型: 参见联动类型定义
       * </pre>
       */
      public int getTriggerType() {
        return triggerType_;
      }
      /**
       * <code>required int32 trigger_type = 1;</code>
       *
       * <pre>
       *联动类型: 参见联动类型定义
       * </pre>
       */
      public Builder setTriggerType(int value) {
        bitField0_ |= 0x00000001;
        triggerType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 trigger_type = 1;</code>
       *
       * <pre>
       *联动类型: 参见联动类型定义
       * </pre>
       */
      public Builder clearTriggerType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        triggerType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> triggerRet_ = java.util.Collections.emptyList();
      private void ensureTriggerRetIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          triggerRet_ = new java.util.ArrayList<java.lang.Integer>(triggerRet_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 trigger_ret = 2;</code>
       *
       * <pre>
       *联动结果
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getTriggerRetList() {
        return java.util.Collections.unmodifiableList(triggerRet_);
      }
      /**
       * <code>repeated int32 trigger_ret = 2;</code>
       *
       * <pre>
       *联动结果
       * </pre>
       */
      public int getTriggerRetCount() {
        return triggerRet_.size();
      }
      /**
       * <code>repeated int32 trigger_ret = 2;</code>
       *
       * <pre>
       *联动结果
       * </pre>
       */
      public int getTriggerRet(int index) {
        return triggerRet_.get(index);
      }
      /**
       * <code>repeated int32 trigger_ret = 2;</code>
       *
       * <pre>
       *联动结果
       * </pre>
       */
      public Builder setTriggerRet(
          int index, int value) {
        ensureTriggerRetIsMutable();
        triggerRet_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 trigger_ret = 2;</code>
       *
       * <pre>
       *联动结果
       * </pre>
       */
      public Builder addTriggerRet(int value) {
        ensureTriggerRetIsMutable();
        triggerRet_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 trigger_ret = 2;</code>
       *
       * <pre>
       *联动结果
       * </pre>
       */
      public Builder addAllTriggerRet(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTriggerRetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, triggerRet_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 trigger_ret = 2;</code>
       *
       * <pre>
       *联动结果
       * </pre>
       */
      public Builder clearTriggerRet() {
        triggerRet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private java.lang.Object triggerTime_ = "";
      /**
       * <code>required string trigger_time = 3;</code>
       *
       * <pre>
       *联动执行时间(确认时为确认时间)
       * </pre>
       */
      public boolean hasTriggerTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string trigger_time = 3;</code>
       *
       * <pre>
       *联动执行时间(确认时为确认时间)
       * </pre>
       */
      public java.lang.String getTriggerTime() {
        java.lang.Object ref = triggerTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            triggerTime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string trigger_time = 3;</code>
       *
       * <pre>
       *联动执行时间(确认时为确认时间)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTriggerTimeBytes() {
        java.lang.Object ref = triggerTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          triggerTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string trigger_time = 3;</code>
       *
       * <pre>
       *联动执行时间(确认时为确认时间)
       * </pre>
       */
      public Builder setTriggerTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        triggerTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string trigger_time = 3;</code>
       *
       * <pre>
       *联动执行时间(确认时为确认时间)
       * </pre>
       */
      public Builder clearTriggerTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        triggerTime_ = getDefaultInstance().getTriggerTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string trigger_time = 3;</code>
       *
       * <pre>
       *联动执行时间(确认时为确认时间)
       * </pre>
       */
      public Builder setTriggerTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        triggerTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object triggerInfo_ = "";
      /**
       * <code>optional string trigger_info = 33;</code>
       *
       * <pre>
       *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
       * </pre>
       */
      public boolean hasTriggerInfo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string trigger_info = 33;</code>
       *
       * <pre>
       *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
       * </pre>
       */
      public java.lang.String getTriggerInfo() {
        java.lang.Object ref = triggerInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            triggerInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trigger_info = 33;</code>
       *
       * <pre>
       *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTriggerInfoBytes() {
        java.lang.Object ref = triggerInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          triggerInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trigger_info = 33;</code>
       *
       * <pre>
       *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
       * </pre>
       */
      public Builder setTriggerInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        triggerInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trigger_info = 33;</code>
       *
       * <pre>
       *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
       * </pre>
       */
      public Builder clearTriggerInfo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        triggerInfo_ = getDefaultInstance().getTriggerInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trigger_info = 33;</code>
       *
       * <pre>
       *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
       * </pre>
       */
      public Builder setTriggerInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        triggerInfo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string err_msg = 34;</code>
       *
       * <pre>
       *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
       *客户端确认信息:user_name;confirm_desc;user_ip;
       * </pre>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string err_msg = 34;</code>
       *
       * <pre>
       *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
       *客户端确认信息:user_name;confirm_desc;user_ip;
       * </pre>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string err_msg = 34;</code>
       *
       * <pre>
       *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
       *客户端确认信息:user_name;confirm_desc;user_ip;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string err_msg = 34;</code>
       *
       * <pre>
       *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
       *客户端确认信息:user_name;confirm_desc;user_ip;
       * </pre>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string err_msg = 34;</code>
       *
       * <pre>
       *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
       *客户端确认信息:user_name;confirm_desc;user_ip;
       * </pre>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string err_msg = 34;</code>
       *
       * <pre>
       *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
       *客户端确认信息:user_name;confirm_desc;user_ip;
       * </pre>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.zdsoft.officework.mqreceive.TriggerResult)
    }

    static {
      defaultInstance = new TriggerResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.zdsoft.officework.mqreceive.TriggerResult)
    public String toJsonString(){
		  JSONObject json = new JSONObject();
		  for (final Map.Entry<FieldDescriptor, Object> field :
		         this.getAllFields().entrySet()) {
		    	json.put(field.getKey().getName(), field.getValue());
		    }
		  return json.toJSONString();
	  }
  }

  public interface CommEventTrigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.zdsoft.officework.mqreceive.CommEventTrig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 trigger_type = 1;</code>
     *
     * <pre>
     *联动类型: 参见联动类型定义blg.proto
     * </pre>
     */
    boolean hasTriggerType();
    /**
     * <code>required int32 trigger_type = 1;</code>
     *
     * <pre>
     *联动类型: 参见联动类型定义blg.proto
     * </pre>
     */
    int getTriggerType();

    /**
     * <code>required bytes trigger_info = 2;</code>
     *
     * <pre>
     *联动内容：参加联动格式定义blg.proto
     * </pre>
     */
    boolean hasTriggerInfo();
    /**
     * <code>required bytes trigger_info = 2;</code>
     *
     * <pre>
     *联动内容：参加联动格式定义blg.proto
     * </pre>
     */
    com.google.protobuf.ByteString getTriggerInfo();
  }
  /**
   * Protobuf type {@code net.zdsoft.officework.mqreceive.CommEventTrig}
   *
   * <pre>
   *&#64;事件联动消息结构体
   * </pre>
   */
  public static final class CommEventTrig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:net.zdsoft.officework.mqreceive.CommEventTrig)
      CommEventTrigOrBuilder {
    // Use CommEventTrig.newBuilder() to construct.
    private CommEventTrig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommEventTrig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommEventTrig defaultInstance;
    public static CommEventTrig getDefaultInstance() {
      return defaultInstance;
    }

    public CommEventTrig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommEventTrig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              triggerType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              triggerInfo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.zdsoft.officework.mqreceive.Comm.CommEventTrig.class, net.zdsoft.officework.mqreceive.Comm.CommEventTrig.Builder.class);
    }

    public static com.google.protobuf.Parser<CommEventTrig> PARSER =
        new com.google.protobuf.AbstractParser<CommEventTrig>() {
      public CommEventTrig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommEventTrig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommEventTrig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRIGGER_TYPE_FIELD_NUMBER = 1;
    private int triggerType_;
    /**
     * <code>required int32 trigger_type = 1;</code>
     *
     * <pre>
     *联动类型: 参见联动类型定义blg.proto
     * </pre>
     */
    public boolean hasTriggerType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 trigger_type = 1;</code>
     *
     * <pre>
     *联动类型: 参见联动类型定义blg.proto
     * </pre>
     */
    public int getTriggerType() {
      return triggerType_;
    }

    public static final int TRIGGER_INFO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString triggerInfo_;
    /**
     * <code>required bytes trigger_info = 2;</code>
     *
     * <pre>
     *联动内容：参加联动格式定义blg.proto
     * </pre>
     */
    public boolean hasTriggerInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes trigger_info = 2;</code>
     *
     * <pre>
     *联动内容：参加联动格式定义blg.proto
     * </pre>
     */
    public com.google.protobuf.ByteString getTriggerInfo() {
      return triggerInfo_;
    }

    private void initFields() {
      triggerType_ = 0;
      triggerInfo_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTriggerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTriggerInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, triggerType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, triggerInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, triggerType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, triggerInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.zdsoft.officework.mqreceive.Comm.CommEventTrig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.zdsoft.officework.mqreceive.Comm.CommEventTrig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.zdsoft.officework.mqreceive.CommEventTrig}
     *
     * <pre>
     *&#64;事件联动消息结构体
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.zdsoft.officework.mqreceive.CommEventTrig)
        net.zdsoft.officework.mqreceive.Comm.CommEventTrigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.zdsoft.officework.mqreceive.Comm.CommEventTrig.class, net.zdsoft.officework.mqreceive.Comm.CommEventTrig.Builder.class);
      }

      // Construct using net.zdsoft.officework.mqreceive.Comm.CommEventTrig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        triggerType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        triggerInfo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.zdsoft.officework.mqreceive.Comm.internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_descriptor;
      }

      public net.zdsoft.officework.mqreceive.Comm.CommEventTrig getDefaultInstanceForType() {
        return net.zdsoft.officework.mqreceive.Comm.CommEventTrig.getDefaultInstance();
      }

      public net.zdsoft.officework.mqreceive.Comm.CommEventTrig build() {
        net.zdsoft.officework.mqreceive.Comm.CommEventTrig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.zdsoft.officework.mqreceive.Comm.CommEventTrig buildPartial() {
        net.zdsoft.officework.mqreceive.Comm.CommEventTrig result = new net.zdsoft.officework.mqreceive.Comm.CommEventTrig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.triggerType_ = triggerType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.triggerInfo_ = triggerInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.zdsoft.officework.mqreceive.Comm.CommEventTrig) {
          return mergeFrom((net.zdsoft.officework.mqreceive.Comm.CommEventTrig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.zdsoft.officework.mqreceive.Comm.CommEventTrig other) {
        if (other == net.zdsoft.officework.mqreceive.Comm.CommEventTrig.getDefaultInstance()) return this;
        if (other.hasTriggerType()) {
          setTriggerType(other.getTriggerType());
        }
        if (other.hasTriggerInfo()) {
          setTriggerInfo(other.getTriggerInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTriggerType()) {
          
          return false;
        }
        if (!hasTriggerInfo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.zdsoft.officework.mqreceive.Comm.CommEventTrig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.zdsoft.officework.mqreceive.Comm.CommEventTrig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int triggerType_ ;
      /**
       * <code>required int32 trigger_type = 1;</code>
       *
       * <pre>
       *联动类型: 参见联动类型定义blg.proto
       * </pre>
       */
      public boolean hasTriggerType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 trigger_type = 1;</code>
       *
       * <pre>
       *联动类型: 参见联动类型定义blg.proto
       * </pre>
       */
      public int getTriggerType() {
        return triggerType_;
      }
      /**
       * <code>required int32 trigger_type = 1;</code>
       *
       * <pre>
       *联动类型: 参见联动类型定义blg.proto
       * </pre>
       */
      public Builder setTriggerType(int value) {
        bitField0_ |= 0x00000001;
        triggerType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 trigger_type = 1;</code>
       *
       * <pre>
       *联动类型: 参见联动类型定义blg.proto
       * </pre>
       */
      public Builder clearTriggerType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        triggerType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString triggerInfo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes trigger_info = 2;</code>
       *
       * <pre>
       *联动内容：参加联动格式定义blg.proto
       * </pre>
       */
      public boolean hasTriggerInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes trigger_info = 2;</code>
       *
       * <pre>
       *联动内容：参加联动格式定义blg.proto
       * </pre>
       */
      public com.google.protobuf.ByteString getTriggerInfo() {
        return triggerInfo_;
      }
      /**
       * <code>required bytes trigger_info = 2;</code>
       *
       * <pre>
       *联动内容：参加联动格式定义blg.proto
       * </pre>
       */
      public Builder setTriggerInfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        triggerInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes trigger_info = 2;</code>
       *
       * <pre>
       *联动内容：参加联动格式定义blg.proto
       * </pre>
       */
      public Builder clearTriggerInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        triggerInfo_ = getDefaultInstance().getTriggerInfo();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.zdsoft.officework.mqreceive.CommEventTrig)
    }

    static {
      defaultInstance = new CommEventTrig(true);
      defaultInstance.initFields();
    }

    public String toJsonString(){
		  JSONObject json = new JSONObject();
		  for (final Map.Entry<FieldDescriptor, Object> field :
		         this.getAllFields().entrySet()) {
		    	json.put(field.getKey().getName(), field.getValue());
		    }
		  return json.toJSONString();
	  }

    // @@protoc_insertion_point(class_scope:net.zdsoft.officework.mqreceive.CommEventTrig)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_zdsoft_officework_mqreceive_TriggerResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_zdsoft_officework_mqreceive_TriggerResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncomm.proto\022\037net.zdsoft.officework.mqre" +
      "ceive\"w\n\rTriggerResult\022\024\n\014trigger_type\030\001" +
      " \002(\005\022\023\n\013trigger_ret\030\002 \003(\005\022\024\n\014trigger_tim" +
      "e\030\003 \002(\t\022\024\n\014trigger_info\030! \001(\t\022\017\n\007err_msg" +
      "\030\" \001(\t\";\n\rCommEventTrig\022\024\n\014trigger_type\030" +
      "\001 \002(\005\022\024\n\014trigger_info\030\002 \002(\014*\201\001\n\nEventSta" +
      "te\022\027\n\023EVENT_STATE_INSTANT\020\000\022\025\n\021EVENT_STA" +
      "TE_START\020\001\022\024\n\020EVENT_STATE_STOP\020\002\022\025\n\021EVEN" +
      "T_STATE_PULSE\020\003\022\026\n\022EVENT_STATE_UPDATE\020\004*" +
      "\321\001\n\nMsgCmdType\022\027\n\021MSG_CMD_TYPE_MASK\020\200\376\003\022",
      "\031\n\024MSG_CMD_MANUAL_EVENT\020\201\002\022\032\n\025MSG_CMD_CO" +
      "NFIRM_EVENT\020\202\002\022\031\n\024MSG_CMD_REPORT_EVENT\020\201" +
      "\004\022\032\n\025MSG_CMD_SUBRECV_EVENT\020\202\004\022\035\n\030MSG_CMD" +
      "_EVENT_NOTIFY_REQ\020\201\006\022\035\n\030MSG_CMD_EVENT_NO" +
      "TIFY_RSP\020\202\006"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_zdsoft_officework_mqreceive_TriggerResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_zdsoft_officework_mqreceive_TriggerResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_net_zdsoft_officework_mqreceive_TriggerResult_descriptor,
        new java.lang.String[] { "TriggerType", "TriggerRet", "TriggerTime", "TriggerInfo", "ErrMsg", });
    internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_net_zdsoft_officework_mqreceive_CommEventTrig_descriptor,
        new java.lang.String[] { "TriggerType", "TriggerInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
