
package net.zdsoft.webservice.binding;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import net.zdsoft.framework.config.Evn;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BindingServiceImplService", targetNamespace = "http://binding.webservice.zdsoft.net", wsdlLocation = "http://192.168.0.36:8020/webservice/wsdlBinding?wsdl")
public class BindingServiceImplService
    extends Service
{

    private final static URL BINDINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BINDINGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BINDINGSERVICEIMPLSERVICE_QNAME = new QName("http://binding.webservice.zdsoft.net", "BindingServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	String urlStr = Evn.getWebUrl()+"/webservice/wsdlBinding?wsdl";
            url = new URL(urlStr);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BINDINGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BINDINGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BindingServiceImplService() {
        super(__getWsdlLocation(), BINDINGSERVICEIMPLSERVICE_QNAME);
    }

    public BindingServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BINDINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public BindingServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BINDINGSERVICEIMPLSERVICE_QNAME);
    }

    public BindingServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BINDINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public BindingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BindingServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BindingService
     */
    @WebEndpoint(name = "BindingServiceImplPort")
    public BindingService getBindingServiceImplPort() {
        return super.getPort(new QName("http://binding.webservice.zdsoft.net", "BindingServiceImplPort"), BindingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BindingService
     */
    @WebEndpoint(name = "BindingServiceImplPort")
    public BindingService getBindingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://binding.webservice.zdsoft.net", "BindingServiceImplPort"), BindingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BINDINGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BINDINGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BINDINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
