
package net.zdsoft.webservice.binding;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BindingService", targetNamespace = "http://binding.webservice.zdsoft.net")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BindingService {


    /**
     * 
     * @param staffBindReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "staffBindingReturn", targetNamespace = "")
    @RequestWrapper(localName = "staffBinding", targetNamespace = "http://binding.webservice.zdsoft.net", className = "net.zdsoft.webservice.binding.StaffBinding")
    @ResponseWrapper(localName = "staffBindingResponse", targetNamespace = "http://binding.webservice.zdsoft.net", className = "net.zdsoft.webservice.binding.StaffBindingResponse")
    public String staffBinding(
        @WebParam(name = "staffBindReq", targetNamespace = "")
        String staffBindReq);

}
